// MODULE: Test-only enabled provider. Not part of runtime configuration and never contacts cloud.
import {createApp} from '../server/app.js';
import {emptyAdvice} from './fixtures.js';
import {emptyAgentContent} from '../client/js/services/agent-schema.js';
import {MemoryAgentBudgetLedger} from '../server/services/agent-budget.js';
const response=emptyAdvice();
response.scopeAssessment={status:'within_supplied_scope',reason:'Fixture'};
response.confidence=.5;
response.safeNextSteps=['Review owned dummy evidence.'];
response.hypotheses=[{title:'AI draft owned capability hypothesis',invariant:'A used dummy approval must not replay.',expectedBehavior:'Replay rejected.',potentialFailure:'Hypothesis only.',technique:'Approval / Capability Context Confusion',who:'Member',what:'Approve',object:'Approval',state:'Used',authority:'Dummy capability',context:'Workspace B'}];
response.reportDraft='# Reviewed AI Report Draft\n\n## Ringkasan\n\nObserved dummy only. Researcher Estimate: Unknown.';
response.findingAnalysis={assessment:'Hypothesis',potentialClass:'Capability lifecycle',brokenInvariant:'Used capability cannot replay',potentialRootCause:'State binding hypothesis',falsePositiveChecks:['Review effective role.'],missingEvidence:['Record exact request.'],potentialImpact:'Unverified',duplicateRisk:'Unknown',safeValidation:['Use owned dummy data.']};
const knowledgeResponse={items:[{id:'mock-actor',kind:'actor',title:'Suggested Finance Actor',content:'Possible actor for owned lab accounts',sourceType:'ai',source:'Model fixture',confidence:.5,verified:false,notes:'Inference only',domainId:'finance',flowId:'finance-flow-1',invariantId:'',techniqueId:'tech_17',steps:[]},{id:'mock-company',kind:'company-overview',title:'Company Overview',content:'Unsupplied company details',sourceType:'ai',source:'Fixture',confidence:.5,verified:false,notes:'Inference only',domainId:'finance',flowId:'',invariantId:'',techniqueId:'',steps:[]}],suggestedDomains:[{id:'saas',reason:'Supplied lab model',sourceType:'ai',source:'Fixture',confidence:.5,verified:false,notes:'Review classification'}],unknownInformation:[]};
const proposal=(kind,values={})=>({kind,title:'QA Agent '+kind,analysis:'Supplied owned dummy context; unverified analysis.',reason:'Researcher review required.',confidence:.6,notes:'AI inference only; no target requests.',relatedTechniqueId:'tech_03',relatedToolId:'',relatedHypothesisId:'',relatedTestId:'',relatedFindingId:'',evidenceIds:[],content:emptyAgentContent(),...values});
function agentFixture(request){
  const {agentId,research,message}=JSON.parse(request.prompt),result={summary:agentId+' reviewed supplied context; no facts or vulnerability confirmed.',confidence:.8,notes:'Fixture only.',proposals:[],actions:[],unknownInformation:[]};
  if(message){result.summary='Possible authorization lifecycle issue. Compare owned denied controls; not confirmed.';result.notes='Scope and role must be verified. #authorization #revocation';result.unknownInformation=['Execution-time role is Unknown.'];result.proposals=[proposal('uncertain-analysis',{title:'QA Message Control Review',relatedFindingId:research.findings[0]?.id||'',evidenceIds:research.evidence.slice(0,2).map(e=>e.id)})];return result;}
  if(agentId==='attack-surface'&&!research.knowledge.actors.some(a=>a.name==='QA Reviewed Agent Reader'))result.proposals=[proposal('actor',{title:'QA Actor Proposal',content:{...emptyAgentContent(),name:'QA Agent Reader',authority:'Owned dummy member'}})];
  if(agentId==='technique')result.actions=[{adapter:'json-parse',toolId:'builtin-json',goal:'Parse owned dummy research JSON',reason:'Local validation only.',input:{query:'',json:'{"owned":true,"phase":"review"}',leftEvidenceId:'',rightEvidenceId:'',url:''},risk:'low',expectedResult:'Parsed JSON',stopConditions:['Invalid JSON','Sensitive data']}];
  if(agentId==='hypothesis'&&!research.hypotheses.some(h=>h.title==='QA Agent Hypothesis reviewed'))result.proposals=[proposal('hypothesis',{title:'QA Agent Hypothesis candidate',content:{...emptyAgentContent(),invariant:'Used owned approval must not replay.',expectedBehavior:'Replay denied.',potentialFailure:'Possible stale authority; not observed yet.',who:'Member',what:'Approve',object:'Approval',state:'Used',authority:'Owned dummy capability',context:'Lab only'}})];
  if(agentId==='test-planner'){const h=research.hypotheses.find(h=>h.title==='QA Agent Hypothesis reviewed');if(h)result.proposals=[proposal('test-plan',{title:'QA Agent Manual Test Plan',relatedHypothesisId:h.id,content:{...emptyAgentContent(),preconditions:'Owned dummy accounts/data; no real funds',steps:'Use owned dummy approval\nRecord replay behavior manually',expectedResult:'Replay denied.'}})];}
  if(agentId==='finding'){const t=research.tests.find(t=>t.result==='failed'&&t.evidenceIds?.length);if(t)result.proposals=[proposal('potential-finding',{title:'QA Agent Potential Replay',relatedTestId:t.id,evidenceIds:t.evidenceIds,content:{...emptyAgentContent(),actualResult:'Invented model result must be replaced',startingAuthority:'Owned dummy member',securityRestriction:'Used approval must not authorize replay',protectedResource:'Approval',rootCause:'State-use check hypothesis',impact:'Observed duplicate owned approval',vulnerabilityClass:'Capability lifecycle'}})];}
  if(agentId==='false-positive')result.summary='Review effective role and a denied control before confirmation.';
  if(agentId==='duplicate')result.summary='Possible variant of supplied lab finding; researcher decides duplicate risk.';
  if(agentId==='report'){const f=research.findings.find(f=>f.title==='QA Confirmed Agent Finding'&&f.status==='confirmed');if(f)result.proposals=[proposal('report',{title:'QA Agent Report Draft',relatedFindingId:f.id,evidenceIds:f.evidenceIds,content:{...emptyAgentContent(),reportMarkdown:'# QA Agent Report Draft\n\nObserved owned dummy response only. Root cause remains a hypothesis.'}})];}
  return result;
}
const app=await createApp({env:{AI_ENABLED:'true',AGENTIC_AI_ENABLED:process.env.QA_AGENTIC==='true'?'true':'false',AI_PROVIDER:'ollama',OLLAMA_MODEL:'mock-model',AI_ALLOWED_MODELS:'mock-model,mock-vision',AI_PRIVACY_MODE:'LOCAL_ONLY'},agentLedger:new MemoryAgentBudgetLedger(),providerFactory:()=>({async complete(request){const message=JSON.parse(request.prompt).message;if(message?.text.includes('QA delayed message'))await new Promise(resolve=>setTimeout(resolve,1000));if(message?.text.includes('QA failed message'))throw new Error('Authorization: Bearer PRIVATE_MOCK_UPSTREAM');return structuredClone(request.schema.properties.proposals?agentFixture(request):request.schema.properties.items?knowledgeResponse:response);}})});
await app.listen({host:'127.0.0.1',port:Number(process.env.QA_PORT)});
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,async()=>{await app.close();process.exit(0);});
