// MODULE: Hash navigation works on HTTP and file:// without a server router.
export const routes=[['dashboard','Dashboard'],['research-details','Research Details'],['review-queue','Review Queue'],['manual-analysis','Manual Analysis'],['agent-history','Agent History'],['tool-inventory','Tool Inventory'],['agentic-settings','Agentic AI'],['targets','Target'],['research-environment','Research Environment'],['scope','Scope'],['attack-surface','Attack Surface'],['boundaries','Trust Boundaries'],['actors','Actors'],['objects','Objects'],['target-intelligence','Target Intelligence'],['domain-knowledge','Domain Knowledge'],['terminology','Terminology'],['business-flows','Business Flows'],['critical-assets','Critical Assets'],['research-questions','Research Questions'],['techniques','Techniques'],['hypotheses','Hypotheses'],['tests','Test Cases'],['queue','Research Queue'],['findings','Findings'],['evidence','Evidence'],['reports','Reports'],['ai','Research Assistant'],['ai-techniques','Technique Advisor'],['ai-tools','Tool Advisor'],['ai-gaps','AI Gap Analyzer'],['ai-findings','Finding Analyzer'],['notes','Research Notes'],['knowledge','Knowledge Base'],['tools','Tool Knowledge'],['helpers','Internal Helpers'],['coverage','Research Gaps'],['settings','Settings'],['ai-provider','AI Provider'],['backup','Backup']];
// Keep deep links/imported bookmarks; only primary workflow destinations belong in the sidebar.
export const navigationGroups=[['Workspace',['dashboard','targets','scope']],['Research',['target-intelligence','attack-surface','business-flows','techniques','hypotheses','tests']],['Results',['evidence','findings','reports']],['Reference',['domain-knowledge','knowledge','helpers']],['AI',['ai','review-queue']],['System',['settings']]];
export const routeSections={surface:[['attack-surface','All'],['actors','Actors'],['objects','Objects'],['boundaries','Trust Boundaries']],intelligence:[['target-intelligence','Target Understanding'],['domain-knowledge','Domain Knowledge'],['terminology','Terminology'],['business-flows','Business Flows'],['critical-assets','Critical Assets'],['research-questions','Research Questions']],settings:[['settings','Settings'],['research-environment','Research Environment'],['tool-inventory','Tool Inventory'],['ai-provider','AI Provider'],['agentic-settings','Agentic AI'],['backup','Backup']],assistant:[['ai','Research Assistant'],['review-queue','Review Queue'],['research-details','Research Details'],['manual-analysis','Manual Analysis'],['agent-history','Agent History']]};
export const currentRoute=()=>{const key=location.hash.slice(1).split('?')[0];return routes.some(r=>r[0]===key)?key:'dashboard';};
export function routeSectionFor(route){
  const key=['ai-techniques','ai-tools','ai-gaps','ai-findings'].includes(route)?'ai':route;
  return Object.keys(routeSections).find(section=>routeSections[section].some(([candidate])=>candidate===key))||null;
}
export function routeTo(key) {if(currentRoute()===key) window.dispatchEvent(new Event('hashchange'));else location.hash=key;}
