import {el,button,empty,download,markdownPreview,escapeHTML} from '../utils.js';
import {generateIndonesianReport} from '../templates/report-id.js';
import {reportSourceFingerprint} from '../services/research-integrity.js';
import {reviewForSharing,prepareShare} from '../services/share-review.js';
export function renderReports(ctx,target) {
  const root=el('div',{},ctx.heading('Indonesian Reports','Review draft laporan faktual sebelum mengirimkannya ke program.'));
  if(!target.findings.length){root.append(empty('Buat atau promosikan test case menjadi finding terlebih dahulu.'));return root;}
  const finding=target.findings.find(f=>f.id===ctx.reportFindingId)||target.findings[0];ctx.reportFindingId=finding.id;
  const select=el('select',{'aria-label':'Finding untuk laporan'},target.findings.map(f=>el('option',{value:f.id},f.title)));select.value=finding.id;select.addEventListener('change',()=>{ctx.reportFindingId=select.value;ctx.render();});
  const editor=el('textarea',{class:'report-editor','aria-label':'Draft laporan Markdown',spellcheck:'false'});
  editor.value=finding.reportMarkdown??generateIndonesianReport(target,finding);
  const preview=el('div');let previewTimer;
  const updatePreview=()=>preview.replaceChildren(markdownPreview(editor.value));updatePreview();
  const sourceStatus=el('p',{role:'status'}),isStale=()=>finding.reportMarkdown!==undefined&&finding.reportSourceFingerprint!==reportSourceFingerprint(target,finding);
  const updateSourceStatus=()=>{sourceStatus.className=isStale()?'notice':'muted';sourceStatus.textContent=isStale()?'Draft stale / source unreviewed. Finding, target, technique, or evidence changed; regenerate or review sources before sharing.':'Draft follows the reviewed source version.';};updateSourceStatus();
  editor.addEventListener('input',()=>{const source=finding.reportMarkdown===undefined?reportSourceFingerprint(target,finding):finding.reportSourceFingerprint;ctx.store.upsert(target.id,'findings',{id:finding.id,reportMarkdown:editor.value,...(source?{reportSourceFingerprint:source}:{})});clearTimeout(previewTimer);previewTimer=setTimeout(updatePreview,150);updateSourceStatus();});
  const share=async()=>{if(isStale()&&!confirm('Draft sources changed or have not been reviewed. Review this draft before sharing. Continue?'))return null;return reviewForSharing(editor.value,{label:'report sharing'});};
  const controls=el('div',{class:'report-controls panel'},select,sourceStatus,el('div',{class:'actions'},button('Generate Report',()=>{if(finding.reportMarkdown!==undefined&&!confirm('Ganti draft yang diedit dengan template terbaru dari finding?'))return;editor.value=generateIndonesianReport(target,finding);ctx.store.upsert(target.id,'findings',{id:finding.id,reportMarkdown:editor.value,reportSourceFingerprint:reportSourceFingerprint(target,finding)});updatePreview();updateSourceStatus();},'primary'),button('Mark Sources Reviewed',()=>{ctx.store.upsert(target.id,'findings',{id:finding.id,reportMarkdown:editor.value,reportSourceFingerprint:reportSourceFingerprint(target,finding)});updateSourceStatus();}),button('Copy Markdown',async()=>{try {const text=await share();if(text===null)return;if(navigator.clipboard && window.isSecureContext)await navigator.clipboard.writeText(text);else {const copy=el('textarea',{},text);document.body.append(copy);copy.focus();copy.select();const copied=document.execCommand('copy');copy.remove();if(!copied)throw new Error('Clipboard unavailable; download the redacted Markdown.');}ctx.toast('Markdown disalin.');}catch(error){ctx.toast(error.message);}}),button('Download .md',async()=>{const text=await share();if(text!==null)download('report.md',text,'text/markdown');}),button('Download .txt',async()=>{const text=await share();if(text!==null)download('report.txt',text);}),button('Download .html',async()=>{const text=await share();if(text!==null)download('report.html','<!doctype html><html lang="id"><meta charset="utf-8"><title>'+escapeHTML(prepareShare(finding.title).redacted)+'</title><body><pre style="white-space:pre-wrap;font:16px/1.6 system-ui;max-width:900px;margin:40px auto">'+escapeHTML(text)+'</pre></body></html>','text/html');}),button('Print',async()=>{const text=await share();if(text===null)return;preview.replaceChildren(markdownPreview(text));window.print();updatePreview();})));
  controls.append(el('p',{class:'muted'},'Generate ulang setelah mengubah finding/evidence. Draft yang diedit disimpan otomatis. Pastikan seluruh secrets telah dire­daksi.'));
  root.append(controls,el('div',{class:'report-layout'},editor,preview));return root;
}
