import {el,button,panel} from '../utils.js';
import {connectFile,saveConnected,connectedFile} from '../storage.js';
import {field} from '../forms.js';
import {reviewForSharing} from '../services/share-review.js';
export function renderSettings(ctx) {
  const root=el('div',{},ctx.heading(ctx.route==='ai-provider'?'AI Provider':ctx.route==='backup'?'Backup & Restore':'Settings & System Health','Core lokal dengan IndexedDB. Backend AI opsional dan tidak menjalankan pengujian target.'));
  const ai=ctx.aiConnection;
  root.append(panel('System Health',el('div',{class:'health-grid'},[['Storage',ctx.storageHealthy?'IndexedDB · OK':'IndexedDB · Error'],['Autosave',ctx.persistence.isDirty()?'Pending':'Active'],['Schema','v2 · 2.0.0'],['AI',ai.status],['Privacy Mode',ai.privacyMode],['Provider',ai.provider||'—'],['Model',ai.model||'—']].map(([label,value])=>el('p',{},el('strong',{},label+': '),value)))));
  const backendForm=el('form',{class:'form-grid'});const backendURL=field(backendForm,['backendURL','Backend localhost origin'],ai.baseURL||'http://127.0.0.1:3001');backendForm.append(el('button',{type:'submit',class:'primary'},'Connect Backend'));backendForm.addEventListener('submit',event=>{event.preventDefault();void ctx.connectBackend(backendURL.value);});
  root.append(panel('Optional AI Provider',el('p',{class:'muted'},'Provider, model, dan API key diatur hanya di .env backend. AI_ENABLED=false tidak menginisialisasi provider. Connected menunjukkan konfigurasi siap; status dapat berubah setelah request provider.'),location.protocol==='file:'?el('p',{class:'notice'},'Untuk AI, jalankan Node backend dan buka http://127.0.0.1:3001. Core file:// tetap offline; backend menolak Origin null.'):backendForm));
  root.append(panel('Workspace backups',el('p',{class:'muted'},'Export berisi seluruh target, research, evidence teks, serta draft laporan. Import mengganti workspace setelah validasi dan confirmation.'),el('div',{class:'actions'},button('Export Workspace',ctx.exportWorkspace,'primary'),button('Import Workspace',ctx.importWorkspace),button('Export Backup',()=>ctx.exportWorkspace(true)))));
  const filePanel=panel('Optional · Connect workspace.json',el('p',{class:'muted'},'File ditulis hanya saat Anda menekan Save to workspace.json. Browser meminta izin native. Hubungan file perlu dibuat kembali setelah reload.'));
  if(window.showSaveFilePicker)filePanel.append(el('p',{},connectedFile.handle?'Terhubung: '+connectedFile.handle.name:'Belum ada file terhubung.'),el('div',{class:'actions'},button('Connect workspace.json',async()=>{try {await connectFile();ctx.render();}catch(error){if(error.name!=='AbortError')ctx.toast(error.message);}}),connectedFile.handle?button('Save to workspace.json',async()=>{try{const text=await reviewForSharing(structuredClone(ctx.store.get()),{allowOriginal:true,label:'connected backup'});if(text===null)return;await saveConnected(JSON.parse(text));ctx.toast('Workspace ditulis ke '+connectedFile.handle.name);}catch(error){ctx.toast('Gagal menulis file: '+error.message);}}):null));
  else filePanel.append(el('p',{class:'notice'},'File System Access API tidak tersedia di browser/context ini. Local persistence dan JSON export tetap tersedia.'));
  root.append(filePanel,panel('Data & privacy',el('p',{},'schemaVersion: 2.0.0 · workspace applicationVersion: '+ctx.store.get().applicationVersion+' / running application: 2.0.0'),el('p',{class:'muted'},'IndexedDB menyimpan data tanpa enkripsi. Journal localStorage opsional membantu recovery ketika tab ditutup. Backup rutin; storage browser dapat dihapus atau penuh.'),el('p',{class:'muted'},'Aplikasi tidak membaca file evidence dari path dan tidak menghubungi aset target. Context AI hanya dikirim setelah Preview dan Send; secrets dire­daksi pada mode REDACTED_CLOUD.'),el('a',{href:ctx.playbookUrl,target:'_blank',rel:'noopener'},'Buka dokumentasi playbook asli ↗')),panel('Reset Workspace',el('p',{class:'muted'},'Menghapus seluruh target dan research dari workspace aktif browser ini. File backup yang sudah diunduh tetap tersedia. Salinan legacy v1 dipertahankan sebagai sumber recovery.'),button('Reset Workspace',()=>{if(confirm('Reset seluruh workspace lokal? Semua target, hypothesis, test, finding, evidence, knowledge, AI suggestion, dan draft laporan akan dihapus. Export Backup sebelum melanjutkan.')){ctx.store.reset();ctx.selectTarget('');ctx.render();}},'danger')));
  return root;
}
