import {el,button,badge,empty} from '../utils.js';
import {editDialog} from '../forms.js';
import {editHypothesis} from './hypotheses.js';
const techniqueFields=[['name','Technique Name','required'],['rarity','Rarity','select',['very-rare','rare','uncommon','common']],['difficulty','Difficulty','select',['advanced','intermediate','easy']],['domain','Domain','select',['state','auth','api','browser','business','infra']],['description','Description','textarea'],['hypothesisTemplate','Hypothesis Template','textarea'],['testTemplate','Test Template','textarea'],['signalsText','Signals (satu per baris)','textarea'],['stopCondition','Stop Condition','textarea'],['notes','Research Notes','textarea']];
techniqueFields.push(['securityInvariant','Security Invariant','textarea'],['falsePositivesText','False Positive Indicators (satu per baris)','textarea'],['researchPriority','Research Priority 0–100','number'],['duplicateRisk','Duplicate Risk 0–100','number'],['testingCost','Testing Cost 0–100','number']);
export const techniqueCategories=['Authorization','Authentication','Session','State Machine','Business Logic','OAuth / SSO','Tenant Isolation','File Boundary','Browser / Extension','API','Realtime / WebSocket','Async / Queue','Webhook','Cache','Parser Differential','Race Condition','Approval / Capability','Sandbox','Trust Boundary','Custom'];
techniqueFields.push(['category','Category','select',techniqueCategories]);
export function renderTechniques(ctx,target) {
  const root=el('div',{},ctx.heading('Technique Library','20 teknik dari playbook, diurutkan dari paling jarang ke paling umum.',button('+ Custom Technique',()=>editTechnique(),'primary')));
  const editTechnique=row=>editDialog(row?'Edit Technique':'Custom Technique',techniqueFields,{researchPriority:50,duplicateRisk:50,testingCost:50,...row,signalsText:(row?.signals||[]).join('\n'),falsePositivesText:(row?.falsePositiveIndicators||[]).join('\n')},values=>{const {signalsText,falsePositivesText,...fields}=values;for(const key of ['researchPriority','duplicateRisk','testingCost']){fields[key]=Number(fields[key]);if(!Number.isFinite(fields[key])||fields[key]<0||fields[key]>100)throw new Error(key+' harus 0–100.');}ctx.store.upsert(target.id,'techniques',{enabled:true,tested:false,interesting:false,dimensions:['who','what','object','state','authority','context'],...row,...fields,signals:signalsText.split('\n').filter(Boolean),falsePositiveIndicators:falsePositivesText.split('\n').filter(Boolean),stopConditions:fields.stopCondition?[fields.stopCondition]:[]});ctx.render();});
  const filters=ctx.filters('techniques',[['rarity','Rarity',['very-rare','rare','uncommon','common']],['difficulty','Difficulty',['advanced','intermediate','easy']],['domain','Domain',['state','auth','api','browser','business','infra']],['category','Category',techniqueCategories]]);root.append(filters);
  const sort=el('select',{'aria-label':'Technique sorting'},['Rare First','Easy First','Highest Research Priority','Lowest Duplicate Risk','Lowest Testing Cost'].map(value=>el('option',{value},value)));sort.value=ctx.techniqueSort||'Rare First';sort.addEventListener('change',()=>{ctx.techniqueSort=sort.value;ctx.render();});root.append(el('div',{class:'filters'},sort));
  const sorters={'Rare First':(a,b)=>({'very-rare':0,rare:1,uncommon:2,common:3}[a.rarity]??4)-({'very-rare':0,rare:1,uncommon:2,common:3}[b.rarity]??4),'Easy First':(a,b)=>({easy:0,intermediate:1,advanced:2}[a.difficulty]??3)-({easy:0,intermediate:1,advanced:2}[b.difficulty]??3),'Highest Research Priority':(a,b)=>(b.researchPriority??50)-(a.researchPriority??50),'Lowest Duplicate Risk':(a,b)=>(a.duplicateRisk??50)-(b.duplicateRisk??50),'Lowest Testing Cost':(a,b)=>(a.testingCost??50)-(b.testingCost??50)};
  const rows=ctx.filtered(target.techniques,'techniques').slice().sort(sorters[sort.value]);
  if(!rows.length)root.append(empty('Tidak ada teknik yang cocok.'));
  for(const row of rows) {
    const toggles=el('div',{class:'actions'});
    for(const [key,label] of [['enabled','Enabled'],['tested','Tested'],['interesting','Interesting']]) {const input=el('input',{type:'checkbox','aria-label':label+' '+row.name});input.checked=!!row[key];input.addEventListener('change',()=>{ctx.store.upsert(target.id,'techniques',{id:row.id,[key]:input.checked});ctx.render();});toggles.append(el('label',{class:'actions'},input,label));}
    const detail=el('details',{class:'technique-details'},el('summary',{},'Invariant / hypothesis / test / signals / false positives / stop'),el('dl',{class:'details'},['securityInvariant','hypothesisTemplate','testTemplate','signals','falsePositiveIndicators','stopCondition','notes'].map(key=>[el('dt',{},({securityInvariant:'Security Invariant',hypothesisTemplate:'Hypothesis',testTemplate:'Test',signals:'Signal',falsePositiveIndicators:'False Positive Indicators',stopCondition:'Stop Condition',notes:'Notes'})[key]),el('dd',{},Array.isArray(row[key])?row[key].join('\n'):row[key]||'—')])));
    root.append(el('article',{class:'record'},el('div',{class:'record-header'},el('h3',{},el('span',{class:'rank'},row.rank?String(row.rank).padStart(2,'0'):'＋'),row.name),el('div',{class:'actions'},button('Buat hypothesis',()=>editHypothesis(ctx,target,null,{techniqueId:row.id,potentialFailure:row.hypothesisTemplate,notes:row.testTemplate}),'primary'),button('Edit',()=>editTechnique(row)))),el('div',{class:'badges'},badge(row.rarity),badge(row.difficulty),badge(row.domain)),el('p',{class:'muted'},row.description||''),toggles,detail));
  }
  return root;
}
