"""Dependency-free compatibility bundle. ES module sources remain the source of truth."""
from pathlib import Path
import re
root=Path(__file__).resolve().parents[1]
ordered=['utils','technique-data','knowledge-data','services/ai-schema','services/redactor','services/rules','services/context','services/analysis','services/ai-client','storage','store','router','forms','modules/targets','modules/scope','modules/attack-surface','modules/techniques','modules/hypotheses','modules/tests','modules/evidence','templates/report-id','modules/findings','modules/reports','modules/dashboard','modules/notes','modules/settings','modules/knowledge','modules/tools','modules/coverage','modules/helpers','modules/ai','app']
parts=['// Generated by scripts/build.py. Do not edit directly.\n(async()=>{\n"use strict";']
for name in ordered:
    source=(root/'client/js'/f'{name}.js').read_text(encoding='utf-8')
    source=re.sub(r'^import .*?;\s*$', '', source, flags=re.M)
    source=re.sub(r'\bexport (?=(?:const|let|function|async function|class)\b)','',source)
    parts.append('// SOURCE: '+name+'\n'+source)
parts.append('})().catch(error=>{document.getElementById("view").textContent="Aplikasi gagal dimuat: "+error.message;});\n')
(root/'client/js/bundle.js').write_text('\n'.join(parts),encoding='utf-8')
print('Local file bundle generated.')
