"""Dependency-free compatibility bundle. ES module sources remain the source of truth."""
from pathlib import Path
import re
import runpy
root=Path(__file__).resolve().parents[1]
runpy.run_path(str(root/'scripts/build-docs.py'),run_name='__main__')
runpy.run_path(str(root/'scripts/build-domains.py'),run_name='__main__')
ordered=['utils','icons','technique-data','knowledge-data','domain-data','feature-registry','help','services/ai-schema','services/domain-schema','services/knowledge-schema','services/redactor','services/message-contract','services/agent-schema','services/environment','services/secret-store','services/rules','services/context','services/analysis','services/local-advice','services/domain-knowledge','services/knowledge-context','services/knowledge-search','services/agent-context','services/agent-messages','services/related-terms','services/research-context-builder','services/ai-client','services/agent-research','storage','store','router','forms','modules/targets','modules/research-environment','modules/agent-message-panel','modules/scope','modules/attack-surface','modules/techniques','modules/hypotheses','modules/tests','modules/evidence','templates/report-id','modules/findings','modules/reports','modules/agent-research','modules/dashboard','modules/notes','modules/settings','modules/knowledge','modules/tools','modules/coverage','modules/helpers','modules/ai','modules/intelligence','app']
ordered.insert(ordered.index('services/message-contract'),'services/research-integrity')
ordered.insert(ordered.index('services/message-contract'),'services/share-review')
ordered.insert(ordered.index('services/message-contract'),'services/message-attachments')
for service in ['research-priority','research-workflow','research-context-selection','research-model','causal-research-graph','contradiction-analyzer','next-hypothesis','discovery-intelligence','advanced-research','research-grounding']:
    ordered.insert(ordered.index('services/agent-context'),'services/'+service)
ordered.insert(ordered.index('modules/targets'),'modules/research-navigation')
ordered.insert(ordered.index('modules/agent-research'),'modules/advanced-research')
parts=['// Generated by scripts/build.py. Do not edit directly.\n(async()=>{\n"use strict";']
for name in ordered:
    source=(root/'client/js'/f'{name}.js').read_text(encoding='utf-8')
    source=re.sub(r'^import .*?;\s*$', '', source, flags=re.M)
    source=re.sub(r'\bexport (?=(?:const|let|function|async function|class)\b)','',source)
    parts.append('// SOURCE: '+name+'\n'+source)
parts.append('})().catch(error=>{document.getElementById("view").textContent="Aplikasi gagal dimuat: "+error.message;});\n')
(root/'client/js/bundle.js').write_text('\n'.join(parts),encoding='utf-8')
print('Local file bundle generated.')
