"""Authoritative feature metadata and researcher reference content.

Edit entries here, then run scripts/build.py. Never put research/user data here.
Technique reference details are read from data/default-techniques.json.
"""
FEATURES = []
TECHNIQUE_EXAMPLES = {
    'tech_01': 'Pada Example SaaS, bandingkan aksi export oleh Member pada state active dan revoked dalam tenant sama; pastikan actor/action/object/state/authority/context yang dicatat cocok keputusan backend.',
    'tech_02': 'Job Export Demo dibuat ketika Member aktif, lalu membership dicabut sebelum worker berjalan. Amati apakah worker atau akses hasil memvalidasi ulang izin, pada timing yang bisa dikendalikan di laboratorium.',
    'tech_03': 'Jika laboratorium Example SaaS memiliki approval export, bandingkan context project/actor/destination yang disetujui dengan context ketika approval dipakai. Catat apakah capability masih valid setelah digunakan.',
    'tech_04': 'Jika klien laboratorium mendukung resume, catat apakah restart/resume memakai capability Member yang sudah revoked. Periksa respons backend aktual, bukan hanya state UI lama.',
    'tech_05': 'Bandingkan penolakan export Member revoked pada Web dan API laboratorium Example SaaS. Gunakan actor/object/state yang sama agar perbedaan surface tidak tercampur ownership.',
    'tech_06': 'Jika ada extension milik peneliti pada laboratorium, petakan Browser → Extension → Backend dan aturan asal pesan sebelum memeriksa protected action. Tanpa extension, pilih teknik lain.',
    'tech_07': 'Catat apakah Export Demo yang dicabut atau dihapus masih dapat diakses melalui authority lama pada dua akun sendiri. Bedakan data cache UI dari akses baru yang diotorisasi backend.',
    'tech_08': 'Pada laboratorium yang mengizinkan kontrol interleaving transaksi, petakan waktu pemeriksaan izin dan perubahan state export. Dokumentasikan observasi terbatas; jangan menganggap pengujian race/volume diizinkan semua program.',
    'tech_09': 'Jika Example SaaS memiliki webhook export ke endpoint laboratorium sendiri, catat tenant/owner destination sebelum dan setelah perubahan konfigurasi. Jangan mengarahkan callback ke endpoint pihak lain.',
    'tech_10': 'Jika laboratorium mengirim progres Export Demo lewat WebSocket, catat apakah channel Member revoked masih menerima event baru. Bedakan event lama di buffer dari event sesudah revoke efektif.',
    'tech_11': 'Jika laboratorium menyediakan beberapa parser input API, bandingkan makna object/action/context dari data dummy yang sama. Catat input dan interpretasi, bukan hanya perbedaan status HTTP.',
    'tech_12': 'Bandingkan respons export yang diperoleh dua akun sendiri pada tenant lab berbeda bila caching memang ada. Gunakan marker dummy terpisah dan periksa authority/variant cache yang relevan.',
    'tech_13': 'Jika OAuth/SSO tersedia di laboratorium sendiri, catat issuer, session, identity dan account-linking untuk akun dummy A/B. Tanpa integrasi yang diotorisasi, teknik tidak digunakan.',
    'tech_14': 'Buat Tenant Demo A/B milik peneliti bila laboratorium mendukungnya; bandingkan akses Member terhadap Project Demo yang ownership-nya berbeda. Isi CONTEXT tenant dan evidence marker secara eksplisit.',
    'tech_15': 'Catat owner, ACL, share expiry dan revoke pada Export Demo dummy; periksa apakah akses file mengikuti izin terkini. Bedakan link publik yang memang didokumentasikan dari protected resource.',
    'tech_16': 'Bandingkan aksi administrasi Project Demo antara Owner dan Member laboratorium. Nyatakan authority yang dibutuhkan dan respons kontrol sebelum menyimpulkan privilege escalation.',
    'tech_17': 'Bandingkan object milik akun A/B sendiri pada Example SaaS. Identifier adalah input resource; expected behavior tetap membutuhkan pemeriksaan ownership/authorization, bukan sekadar identifier valid.',
    'tech_18': 'Petakan transisi export queued → processing → ready dan prasyaratnya di laboratorium. Dokumentasikan apakah aksi Member memenuhi state dan authority yang seharusnya berlaku.',
    'tech_19': 'Catat apakah session akun B masih memberi akses export baru setelah logout/expiry/revoke yang sudah efektif. Gunakan kontrol untuk membedakan session aktif lain atau capability terpisah.',
    'tech_20': 'Pada API laboratorium Example SaaS, catat perbedaan validasi/konfigurasi dan protected outcome menggunakan input dummy terbatas. Perbedaan error saja belum membuktikan dampak keamanan.'
}
TOOL_DESCRIPTIONS = {
    'burp-repeater': 'Membandingkan request secara manual dan terkontrol.',
    'caido': 'Workflow proxy/replay manual; aksi otomatis memerlukan izin program terpisah.',
    'mitmproxy': 'Memeriksa traffic yang diotorisasi; script otomatis tidak termasuk mode rekomendasi ini.',
    'postman': 'Mengirim dan memeriksa satu request API yang diotorisasi secara manual.',
    'curl': 'Mencatat request manual ke endpoint yang diotorisasi.',
    'jq': 'Membandingkan dan memfilter JSON lokal.',
    'browser-devtools': 'Memeriksa state lokal, catatan network, dan context aplikasi.',
    'wireshark': 'Memeriksa file capture traffic lokal yang diotorisasi.',
    'git': 'Mencatat perubahan notes atau fixture milik peneliti secara lokal.',
    'docker': 'Reproduksi pada lingkungan uji terisolasi milik peneliti.',
    'websocat': 'Memeriksa koneksi WebSocket yang diotorisasi secara manual.'
}


def add(id, name, description, purpose, when, inputs, outputs, how, example,
        related, tips, status='Active', routes=(), operation=None, helper=None):
    FEATURES.append(dict(id=id, name=name, description=description, purpose=purpose,
                         status=status, routes=list(routes), operation=operation,
                         helper=helper, when=when, inputs=inputs, outputs=outputs,
                         how=how, example=example, related=related, tips=tips))


add('dashboard', 'Dashboard',
    'Ringkasan jumlah catatan, progress teknik, coverage, dan antrean target aktif.',
    'Membantu memilih pekerjaan berikutnya berdasarkan riset yang sudah dicatat.',
    'Saat membuka engagement dan sebelum menentukan test berikutnya.',
    'CURRENT TARGET; hypotheses, test cases, findings, actors, objects, states, boundaries dan enabled techniques.',
    'Hypotheses total; Tested; Interesting; Confirmed Findings; Rejected; Out of Scope; rasio coverage; progress bar per technique; antrean Next/Testing/Interesting.',
    '1. Pilih target di header.\n2. Buka Dashboard.\n3. Baca metrik, coverage dan queue.\n4. Buka Research Gaps atau buat hypothesis berikutnya.',
    'Example SaaS memiliki dua actor dan satu test Member; Actor Coverage dapat menunjukkan 1 / 2.',
    'Membaca data modul riset; tautan menuju Scope, mapping, Techniques, Hypotheses, Tests, Evidence, Findings, Reports dan Coverage.',
    'Interesting menjumlah hypothesis status interesting dan test result interesting, sehingga bukan jumlah kasus unik. Confirmed Findings hanya menghitung status confirmed, bukan reported/resolved. Tested menghitung test selain not-tested. Progress bar adalah hasil tercatat / seluruh test yang dibuat per technique; bukan quota semua kemungkinan. AI status dan System Health berada di Settings, bukan panel Dashboard.', routes=['dashboard'])

add('targets', 'Target Management',
    'Membuat, memilih, mengedit, dan menghapus profil engagement beserta konteks aset.',
    'Memisahkan riset tiap program dan menyediakan identitas target untuk laporan.',
    'Pertama kali memulai program atau berganti aset/engagement.',
    'Program Name wajib; Platform Bugcrowd/HackerOne/Intigriti/Private/Other; Program URL; Target / Asset; Environment; Version / Build; Status active/paused/archived; Custom Notes.',
    'Target baru dengan ID, timestamps, koleksi riset kosong, tiga program rules false, dan salinan 20 techniques.',
    '1. Target → + Create Target.\n2. Isi nama dan profil.\n3. Simpan.\n4. Pilih target lewat kartu atau CURRENT TARGET.\n5. Gunakan Edit jika konteks berubah.',
    'Program Example SaaS; Asset https://app.example.test; Environment laboratorium sendiri; Version demo-1.',
    'Semua modul riset/KB/helpers/AI suggestions berada pada target ini; Reports mengambil target terdampak dari profil aktif.',
    'Program URL hanya referensi teks, tidak di-fetch. Status paused/archived tidak mengunci riset. Hapus target menghapus semua isinya setelah konfirmasi: ekspor backup dahulu.', routes=['targets'])

add('scope', 'Scope Management',
    'Catatan batas aset, aturan, known issues, dan resource pengujian yang diotorisasi.',
    'Menentukan pertanyaan yang boleh diuji sebelum merencanakan tindakan.',
    'Sebelum mapping, advisor, dan pengujian; review lagi jika rules berubah.',
    'In Scope, Out of Scope, Known Issues, Rate Limits, Automation Rules, Safe Harbor Notes, Testing Restrictions, Test Accounts alias, Owned Domains, Test Workspaces, Dummy Markers.',
    'Scope per target yang autosave dan dipakai context/rules serta review manual.',
    '1. Buka Scope.\n2. Salin batas program sebagai catatan yang sudah direview.\n3. Catat akun/data sendiri dan stop conditions.\n4. Tunggu Saved locally.',
    'Example SaaS hanya laboratorium https://app.example.test, Tenant Demo, dua akun sendiri; layanan pihak ketiga out-of-scope.',
    'Engagement Guard dan Hard Program Rules melengkapi scope; Scope Checker, Tool Knowledge dan AI menerima catatan ini.',
    'Jangan menyimpan password di Test Accounts. Scope bukan parser rules otomatis; daftar teks dan izin pemilik tetap harus diperiksa peneliti.', routes=['scope'])

add('engagement-guard', 'Engagement Guard',
    'Tujuh checklist konfirmasi manual sebelum menjalankan pengujian.',
    'Mengurangi lupa memeriksa izin, data, rate limit dan pembatasan.',
    'Sesudah membaca program rules dan sebelum setiap rangkaian test.',
    'Target confirmed in-scope; testing account authorized; testing data owned; automation rules understood; rate limits understood; restrictions reviewed/destructive testing understood; known issues reviewed.',
    'Flags guard tersimpan dalam scope target. Tiga flags pertama memengaruhi gating rekomendasi.',
    '1. Scope → Engagement Guard.\n2. Review bukti/ketentuan masing-masing.\n3. Centang hanya yang sudah Anda konfirmasi.\n4. Hapus centang jika konfirmasi tidak lagi berlaku.',
    'Owner/Member Example SaaS adalah akun uji sendiri; centang account/data setelah ownership diperiksa.',
    'Scope Checker dan AI context membaca konfirmasi target, akun dan data. Empat checklist lain tetap membantu review manual.',
    'Checklist tidak membuktikan izin secara independen. Automation rules understood berbeda dari automationAllowed. Mengisi checkbox tidak menjalankan test atau memberi izin hukum.')

add('rules-engine', 'Hard Program Rules dan Rules Engine',
    'Program rules membatasi kandidat dan rekomendasi AI melalui policy filter.',
    'Menjaga rekomendasi mengikuti aturan engagement yang dicatat peneliti.',
    'Sebelum meminta rekomendasi tools/techniques dan setiap rules berubah.',
    'automationAllowed, dosAllowed, thirdPartyTesting; asset, In/Out of Scope, tiga guard awal, restrictions dan automation rules. Ketiga izin default false.',
    'Scope assessment within_supplied_scope/outside_supplied_scope/unclear_scope/requires_manual_review; restrictions; kandidat yang lolos filter dan output AI yang difilter kembali.',
    '1. Scope → Hard Program Rules.\n2. Centang izin hanya bila program eksplisit mengizinkan.\n3. Periksa Scope Checker.\n4. Review rekomendasi sesuai rules asli.',
    'automationAllowed=false membatasi kandidat automation. Workspace tetap tidak menyarankan mass scanning; tindakan destructive, credential attack dan mass fuzzing difilter walaupun flag automation true.',
    'Program Rules → Hard Policy Filter → Technique / Tool Candidates → AI Recommendation → output filter → Researcher Decision.',
    'AI tidak bisa mengubah flags. Asset out-of-scope dibanding sebagai teks persis yang dinormalisasi, bukan wildcard/path matching. Asset + In Scope + tiga guard memadai untuk within_supplied_scope walaupun asset belum terbukti cocok daftar scope; review manual wajib. Filter bahasa berbasis pola tidak menjamin seluruh narasi AI aman.')

add('actors', 'Actors',
    'Daftar pelaku/peran dan authority yang relevan untuk pengujian.',
    'Membuat perbedaan hak antarrole terlihat ketika menilai authorization.',
    'Saat mapping dan sebelum mengisi WHO pada hypothesis/test.',
    'Actor / Role wajib; Authority; Notes. Nama bebas, termasuk Anonymous, User, Viewer, Member, Editor, Admin, Owner, Service Account.',
    'Catatan actor per target dan saran nama pada form WHO.',
    '1. Actors → + Tambah.\n2. Isi role dan authority aktual.\n3. Simpan.\n4. Pakai nama yang sama pada hypothesis/test. Edit/hapus sesuai kebutuhan.',
    'Member Example SaaS boleh export saat membership aktif; Owner dapat mencabut Member.',
    'Attack Surface menampilkan actor; Hypotheses/Tests/Findings memakai snapshot WHO; Coverage mencocokkan nama actor.',
    'Actor bukan akun target yang dibuat otomatis. Rename tidak memperbarui snapshot WHO lama; ejaan berbeda mengubah matching coverage.', routes=['actors'])

add('objects', 'Objects',
    'Daftar protected resource, ownership, tenant, state, dan sensitivitasnya.',
    'Membantu membedakan object yang memang boleh diakses dari akses tidak sah.',
    'Saat mapping dan merancang pembanding ownership/tenant/lifecycle.',
    'Object Name wajib; Type Account/File/Project/Workspace/Conversation/Token/Invitation/Approval/Invoice/Webhook/Job/Profile/API Resource/Custom; Owner; Tenant; State; Sensitivity; Notes.',
    'Catatan object, saran OBJECT pada editor, dan state yang masuk denominator coverage.',
    '1. Objects → + Tambah.\n2. Pilih tipe terdekat dan isi ownership/state.\n3. Simpan.\n4. Gunakan nama konsisten pada hypothesis/test.',
    'Project Demo bertipe Project; Export Demo bertipe File, Tenant Demo, state queued. Export bukan tipe dropdown tersendiri.',
    'Attack Surface, Hypotheses, Tests, Findings, AI context dan Coverage memakai catatan ini.',
    'Owner/tenant/state adalah teks manual, bukan hasil sinkronisasi resource target. Update object tidak mengubah snapshot test historis.', routes=['objects'])

add('attack-surface', 'Attack Surface Mapping',
    'Tampilan gabungan Actors, Objects, dan Trust Boundary Map untuk mapping manual.',
    'Menghubungkan pelaku, resource, komponen dan perpindahan authority.',
    'Sebelum memilih technique dan saat arsitektur berkembang.',
    'Actor/object/boundary records; nama komponen pada From/To, channel dan notes; Custom Notes profil untuk arsitektur tambahan.',
    'Kartu daftar tiga jenis entri. Belum ada inventaris surface/endpoint terpisah, discovery, atau graph arsitektur otomatis.',
    '1. Catat arsitektur di Custom Notes/Notes.\n2. Attack Surface → tambah actor/object/boundary.\n3. Gunakan nama Web, API, Desktop, Mobile, Browser Extension, WebSocket, Worker, Storage, OAuth jika relevan.\n4. Catat protokol/endpoint pada Channel/Notes.',
    'Example SaaS: Browser → Backend API → Export Worker → Storage; OAuth hanya ditambahkan jika ada di laboratorium.',
    'Menggabungkan data Actors/Objects/Boundaries yang juga bisa diedit lewat menu masing-masing.',
    'Status Partial menandai mapping yang terbatas pada daftar manual. Menulis endpoint bukan berarti aplikasi menemukan atau menguji endpoint.', status='Partial', routes=['attack-surface'])

add('boundaries', 'Trust Boundaries',
    'Hubungan komponen dengan trust atau privilege berbeda, beserta aturan authority.',
    'Mengidentifikasi titik ketika izin/context dapat berubah atau hilang.',
    'Saat mapping hubungan komponen dan memilih boundary test.',
    'From dan To wajib; Channel; Trust restricted/trusted/untrusted; Authority; Notes.',
    'Row From → To tersimpan dan pilihan Trust Boundary pada test editor.',
    '1. Trust Boundaries → + Tambah.\n2. Isi komponen asal/tujuan dan channel.\n3. Jelaskan authority yang harus diverifikasi.\n4. Pilih row ini pada Test Case yang relevan.',
    'Backend API → Export Worker melalui queue; worker wajib mengecek Member masih aktif. Browser → Extension → Backend → Worker → Storage dapat dicatat sebagai beberapa row.',
    'Attack Surface menampilkan row; Trust Boundary Mapper membuka editor ini; Tests mengaitkan boundary ID; Coverage membaca relasi eksplisit.',
    'Label trust mencatat klasifikasi manual. From/To bukan node graph yang memvalidasi arsitektur. Hapus boundary melepas relasi test, tanpa menghapus test.', routes=['boundaries'])

add('technique-library', 'Technique Library',
    '20 teknik bawaan dan custom technique dengan invariant, template, signals, dan stop condition.',
    'Memberi kerangka memilih pertanyaan keamanan yang sesuai arsitektur dan scope.',
    'Sebelum hypothesis atau saat memilih gap berikutnya.',
    'Search/filter rarity, difficulty, domain, category; sort Rare First/Easy First/Highest Research Priority/Lowest Duplicate Risk/Lowest Testing Cost; editor name, description, invariant, templates, signals, false positives, stop condition, notes dan skor 0–100.',
    'Kartu teknik target dengan Enabled/Tested/Interesting manual, detail referensi, dan tombol Buat hypothesis. Metadata dimensions enam formula tersimpan pada teknik awal.',
    '1. Techniques → filter dan buka detail.\n2. Pilih invariant yang sesuai.\n3. Edit nilai/skor jika perlu.\n4. Buat hypothesis dan lengkapi invariant.\n5. Gunakan + Custom Technique untuk pendekatan yang belum ada.',
    'Async Authorization / Queue Revalidation dipilih untuk memeriksa permission worker ketika membership berubah setelah enqueue.',
    'Teknik menjadi referensi Hypotheses/Tests/Findings, kandidat Technique Advisor, tag Tool Knowledge, dan denominator Coverage jika enabled.',
    'Tested/Interesting tidak disinkronkan dengan hasil test. Custom/edit bersifat per target. Kategori tersedia mencakup Authorization, Authentication, Session, State Machine, Business Logic, OAuth / SSO, Tenant Isolation, File Boundary, Browser / Extension, API, Realtime / WebSocket, Async / Queue, Webhook, Cache, Parser Differential, Race Condition, Approval / Capability, Sandbox, Trust Boundary, Custom. Sandbox belum memiliki teknik bawaan tersendiri. Rincian seluruh 20 teknik tercantum di bawah.', routes=['techniques'])

add('hypotheses', 'Hypotheses',
    'Dugaan kegagalan security invariant yang dipisahkan dari observasi pengujian.',
    'Mencegah asumsi root cause atau impact dianggap sebagai fakta terlalu dini.',
    'Setelah memilih technique dan sebelum membuat test.',
    'Title wajib; Technique; Invariant; Expected Behavior; Potential Failure; WHO/WHAT/OBJECT/STATE/AUTHORITY/CONTEXT; Priority high/medium/low; Confidence low/medium/high; Status idea/planned/testing/interesting/confirmed/rejected/duplicate/out-of-scope; Queue Backlog/Next/Testing/Interesting/Done; Notes.',
    'Hypothesis editable yang dapat menghasilkan beberapa Test Cases dan dipindahkan dalam queue.',
    '1. + Create Hypothesis atau Buat hypothesis dari library.\n2. Nyatakan invariant dan dugaan terpisah.\n3. Isi formula, priority/confidence/status.\n4. Simpan lalu Buat Test Case.',
    'Invariant: Revoked Member tidak boleh melakukan export. Potential Failure: background worker masih memakai authorization lama.',
    'Menerima template technique/manual helper/draft AI yang direview. Test menyimpan hypothesisId; promotion finding mengambil invariant/potential failure.',
    'Status confirmed adalah keputusan peneliti, tidak otomatis membuat finding confirmed. Queue dan status terpisah. Menghapus hypothesis melepas referensi test, bukan menghapus observasi.', routes=['hypotheses'])

add('tests', 'Test Cases',
    'Rencana dan hasil pengujian manual dengan expected/actual, formula, serta evidence.',
    'Memungkinkan review dan reproduksi dengan kondisi pengujian yang jelas.',
    'Sesudah hypothesis; diedit lagi setelah menjalankan tindakan terotorisasi.',
    'Title wajib; Hypothesis/Technique; Preconditions; Steps satu per baris; Expected/Actual Result; enam dimensi; Request/Response Notes; Security Control; Timestamp; Trust Boundary; Research Notes; evidence selection.',
    'Test record, label hasil, relasi evidence/boundary, kontribusi coverage, dan draft finding bila dipromosikan.',
    '1. Hypothesis → Buat Test Case atau + Create Test Case.\n2. Isi kondisi/langkah; pilih boundary.\n3. Simpan NOT TESTED.\n4. Lakukan test sendiri.\n5. Isi actual/evidence/timestamp dan hasil.\n6. Review sebelum Promote to Finding.',
    'Pada Example SaaS, expected akses export ditolak sesudah revoke. PASS jika kontrol bekerja; FAIL jika invariant gagal; INCONCLUSIVE bila timing belum jelas; NOT TESTED jika belum diuji. VULNERABILITY adalah opsi tambahan untuk konfirmasi peneliti.',
    'Menerima hypothesis/template; Evidence dikaitkan; Findings menerima promotion; Dashboard dan Coverage membaca hasil.',
    'FAIL bukan aplikasi test rusak. Hasil tercatat tidak membuktikan seluruh resource aman. Promosi tersedia pada semua hasil dan selalu membuka draft, bukan konfirmasi otomatis. Queue/status hypothesis tetap diubah sendiri.', routes=['tests'])

add('queue', 'Research Queue',
    'Antrean hypothesis dalam lima tahap pekerjaan yang dipilih manual.',
    'Memisahkan rencana prioritas berikutnya dari status kebenaran dugaan.',
    'Ketika merencanakan sesi riset dan menutup tindak lanjut.',
    'Hypotheses, filters, dan pilihan Queue Backlog/Next/Testing/Interesting/Done pada setiap kartu.',
    'Lima kolom berisi judul/jumlah hypothesis dan dropdown perpindahan. Menu Hypotheses juga memuat queue yang sama.',
    '1. Buka Research Queue.\n2. Taruh ide di Backlog, calon sesi berikutnya di Next.\n3. Pindah Testing saat bekerja.\n4. Interesting untuk tindak lanjut; Done ketika ditutup.\n5. Perbarui status hypothesis terpisah.',
    'Dugaan export revoke berada di Next sebelum pengujian dan Interesting ketika butuh bukti timing.',
    'Queue milik Hypotheses; Dashboard menampilkan Next/Testing/Interesting.',
    'Tidak ada drag-and-drop atau transisi otomatis. Done dapat berisi dugaan rejected maupun confirmed; Queue Done tidak sama dengan finding reported.', routes=['queue'])

add('evidence', 'Evidence',
    'Menyimpan teks observasi dan metadata referensi file yang terkait test/finding.',
    'Mendukung reproduksi serta membatasi laporan pada bukti yang tersedia.',
    'Selama/sesudah test dan sebelum review finding/report.',
    'Label wajib; Type screenshot/http-request/http-response/console-output/log/video-reference/file-reference/manual-note; Path/reference; Description; Content; Test Case/Finding associations.',
    'Evidence record dan evidenceIds pada test/finding terkait. Teks/metadata ikut workspace dan report; file binary tidak ikut.',
    '1. Test/Finding → Attach Evidence atau Evidence → + Attach Evidence.\n2. Redaksi teks sebelum memasukkan.\n3. Isi label, type, description dan relasi.\n4. Simpan dan periksa daftar evidence terkait.',
    'Response dummy berisi SECRET_ACCOUNT_A_123 pada export akun A; akun B memakai SECRET_ACCOUNT_B_456. Kedua marker adalah label dummy untuk melacak asal data, bukan secret sebenarnya.',
    'Tests/Findings memilih evidenceIds; promotion menyalin evidence test yang ada saat itu; Reports memasukkan teksnya; AI menerima evidence hanya opt-in.',
    'Warning tidak otomatis meredaksi sebelum Save. Path bukan upload/binary/open-file. Evidence yang ditambahkan setelah promotion perlu dikaitkan juga ke finding. Marker tidak disisipkan/dideteksi otomatis. Hapus evidence melepas relasi dari test/finding.', routes=['evidence'])

add('findings', 'Findings dan Promotion',
    'Kandidat temuan dengan authority, restriction, resource, observasi, impact, dan evidence.',
    'Menyusun hasil test menjadi materi review dan laporan tanpa mencampur dugaan dengan fakta.',
    'Ketika observasi layak ditinjau sebagai temuan setelah review scope dan kontrol.',
    'Title wajib; Status draft/investigating/confirmed/reported/resolved/duplicate/rejected/out-of-scope; Severity Unknown/P1–P5 Researcher Estimate; Component/Version/Class/Technique/Source Test; enam dimensi; Starting Authority; Restriction; Protected Resource; Unauthorized Outcome; Root Cause Hypothesis; Impact; Preconditions/Steps/Expected/Actual; Mitigation; Research Notes; Evidence.',
    'Finding editable. Promotion menyalin source test/formula/expected/actual/steps/evidence dan invariant/potential failure hypothesis, lalu membuka status draft dan severity Unknown.',
    '1. Test → Promote to Finding atau + Create Finding.\n2. Periksa semua nilai prefill.\n3. Lengkapi restriction/resource/impact/evidence.\n4. Review false positives dan duplicate.\n5. Tentukan status/severity sendiri; Generate Report.',
    'Example SaaS: Component Export Worker; Resource Export Demo; outcome akun B memperoleh file setelah revoke hanya jika benar teramati. Root cause snapshot authorization tetap hipotesis.',
    'Affected Target berasal dari current target, bukan field independen. Source test/hypothesis menyediakan draft; checklist/analyzers/Reports memakai finding.',
    'Root cause tidak otomatis terbukti. P1–P5 bukan CVSS atau keputusan program. Menyimpan/mempromosikan tidak otomatis confirmed. Request/response notes test tidak langsung menjadi field finding; lampirkan bukti yang relevan.', routes=['findings'])

add('reports', 'Report Generator',
    'Template laporan Indonesia yang dapat diedit, dipreview, disalin, diekspor, dan dicetak.',
    'Menyajikan fakta dan evidence dalam struktur review yang konsisten.',
    'Setelah finding lengkap dan direview; regenerate setelah facts/evidence berubah.',
    'Finding pilihan, target, technique terkait, evidenceIds dan reportMarkdown yang diedit.',
    'Laporan berisi Ringkasan, Target, Severity Estimate, Prasyarat, Starting Authority, Restriction, Steps, Expected/Actual, Impact, Root Cause Hypothesis, Evidence, Mitigation, Catatan; Copy Markdown; file .md/.txt/.html; Print.',
    '1. Finding → Generate Report.\n2. Di Reports pilih finding dan tekan Generate Report untuk menyimpan template.\n3. Preview dan edit.\n4. Review redaksi.\n5. Copy/download/print.',
    'Laporan export Example SaaS memuat severity Unknown dan root cause berlabel hipotesis sampai peneliti memiliki bukti tambahan.',
    'Membaca Findings/Target/Evidence; draft disimpan di finding.reportMarkdown; Report Assistant dapat menghasilkan draft pengganti yang harus diterima eksplisit.',
    'Template default Indonesia; input user tidak diterjemahkan. Preview hanya heading sederhana dan paragraf, bukan full Markdown. HTML adalah Markdown escaped dalam pre. Draft tersimpan tidak otomatis diperbarui ketika finding berubah; Generate ulang meminta konfirmasi. Aplikasi tidak membuat submission program.', routes=['reports'])

add('notes', 'Research Notes',
    'Scratchpad target dan catatan tambahan hasil import, redaksi, atau review AI.',
    'Menyimpan observasi sementara, pertanyaan dan alasan keputusan tanpa memaksanya menjadi finding.',
    'Sepanjang riset dan sebelum memindahkan lesson ke Knowledge Base.',
    'Teks/Markdown pada scratchpad dan editor note non-scratchpad.',
    'Satu scratchpad per target dan catatan lain yang dapat diedit/delete; autosave content.',
    '1. Research Notes → ketik observasi.\n2. Tunggu Saved locally.\n3. Edit note tambahan hasil AI/import bila perlu.\n4. Pindahkan lesson terstruktur ke KB manual.',
    'Catat urutan waktu enqueue/revoke/execute/download Example SaaS sebelum menyimpulkan kontrol gagal.',
    'AI Accept as Note dan Secret Redactor Save Redacted Note menambahkan note; Global Search mencarinya.',
    'Markdown disimpan sebagai teks, tanpa preview kaya. Jangan menyimpan kredensial hanya karena note lokal; IndexedDB tidak terenkripsi.', routes=['notes'])

add('knowledge', 'Knowledge Base',
    'Catatan terstruktur untuk pola riset, false positive, disclosed report, dan lessons per target.',
    'Menghindari pengulangan investigasi serta menyimpan alasan kontrol bekerja atau gagal.',
    'Sesudah review test/finding dan ketika mempelajari issue sebelumnya.',
    'Title wajib; Category Technique Notes/Research Patterns/False Positives/Finding Patterns/Program Notes/Architecture Patterns/Lessons/Disclosed Reports; Content; Source; Root Cause; Security Boundary; Primitive; Component; Impact.',
    'Knowledge records yang dapat dicari/filter/edit/delete; kandidat duplicate comparator dari tiga kategori tertentu.',
    '1. Knowledge Base → + Add Knowledge.\n2. Pilih kategori dan isi lesson/source.\n3. Lengkapi metadata bila ingin membandingkan duplicate.\n4. Simpan dan gunakan filter untuk mencari.',
    'Lesson Example SaaS: catat waktu eksekusi worker, bukan hanya waktu job dibuat. Simpan kontrol PASS sebagai pelajaran juga.',
    'Duplicate Comparator membaca Disclosed Reports/Finding Patterns/False Positives target aktif. AI menerima KB hanya Include Knowledge Base. Backup membawa seluruh KB.',
    'KB per target, belum shared lintas target atau auto retrieval. Salin lesson yang relevan ke target baru secara manual. Source/disclosed URL adalah teks, bukan fetch. Import JSON mengganti workspace, bukan menggabungkan KB.', routes=['knowledge'])

add('tools', 'Tool Knowledge dan Offline Tool Recommendation',
    'Rekomendasi katalog tools manual berdasarkan technique dan hard scope filter, tanpa AI.',
    'Menghubungkan kebutuhan observasi dengan alat yang relevan dalam batas izin.',
    'Sesudah memilih technique atau untuk melihat opsi manual yang tersedia.',
    'Target, asset/scope/guard/rules, pilihan technique atau Semua teknik; domain dan tag authorization/realtime.',
    'Tool yang lolos policy, urutan relevance, kategori, mode manual, deskripsi, scope warning dan referensi dokumentasi; daftar helper internal.',
    '1. Lengkapi Scope/Guard.\n2. Tool Knowledge → pilih technique.\n3. Baca mode penggunaan dan scope warning.\n4. Buka tool eksternal sendiri jika memang diperlukan dan diizinkan.',
    'IDOR / BOLA / Object Ownership adalah technique; Burp Repeater adalah tool eksternal; Authorization Matrix Builder adalah helper internal untuk ownership/permission rows.',
    'Teknik/scope memberi kandidat offline; AI Tool Advisor meranking kandidat katalog yang dibatasi backend; Helpers menyediakan fitur internal.',
    'Bukan katalog tanpa konteks: asset/scope/guard/rules memengaruhi gating, domain/tag memengaruhi relevance. Tidak ada scanning/probing target. Semua entri curated manual; konfigurasi otomatis tool tidak dicakup. URL dokumentasi tool tampil sebagai teks di kartu.', routes=['tools'])

add('helpers', 'Internal Helpers',
    'Sebelas alat internal lokal untuk menyusun, membandingkan, dan meninjau catatan.',
    'Menyediakan dukungan praktis riset tanpa membutuhkan provider AI.',
    'Saat mapping, merancang test, membersihkan evidence, atau mereview finding.',
    'Pilihan Internal Helper; input manual yang berbeda menurut helper.',
    'Rows/notes/hypotheses tersimpan bila ada Save; hasil perbandingan/preview lokal; atau tautan ke modul terkait.',
    '1. Internal Helpers → pilih helper.\n2. Baca ? untuk input/output/batasannya.\n3. Isi dan jalankan action lokal.\n4. Simpan secara eksplisit jika helper menyediakan Save.',
    'Example SaaS menggunakan State Transition untuk revoke, Secret Redactor untuk log, dan Finding Checklist sebelum report.',
    'Helper Advisor AI merekomendasikan nama dari katalog ini, tanpa membuka/mengeksekusinya. Setiap helper memiliki entri tersendiri di bawah.',
    'Helper adalah fitur aplikasi; Burp/curl/Docker adalah tool eksternal. Evidence Comparator dan Duplicate Comparator menghasilkan preview yang hilang saat pindah view.', routes=['helpers'])

add('helper-authorization-matrix', 'Authorization Matrix Builder',
    'Menyimpan row manual actor × object × action dengan expected permission.',
    'Membuat kontrol permission yang diharapkan eksplisit sebelum membandingkan role.',
    'Saat mapping hak actor atau menyiapkan kontrol pembanding authorization.',
    'Actor, Object, Action wajib; Required Authority; Expected permission/invariant.',
    'helperRecords tipe authorization-matrix dalam kartu row yang dapat diedit/delete.',
    '1. Internal Helpers → Authorization Matrix Builder.\n2. + Add Row.\n3. Isi actor/object/action dan expected permission.\n4. Simpan; ulangi untuk role lain.',
    'Owner → export → Project Demo diizinkan; Member revoked → export → Project Demo harus ditolak.',
    'Menggunakan nama mapping sebagai teks; hasil menjadi referensi manual untuk hypothesis/test.',
    'Partial: belum menghasilkan matriks seluruh kombinasi atau test otomatis. Row tidak menambah coverage dan tidak memverifikasi permission aktual.', status='Partial', helper='authorization-matrix')

add('helper-state-transition', 'State Transition Builder',
    'Menyimpan row state asal/tujuan, action, authority, dan invariant.',
    'Mengidentifikasi kapan hak harus berubah sepanjang lifecycle.',
    'Sebelum test revoke/expiry/approval/async state.',
    'From State dan To State wajib; Action; Required Authority; Security Invariant; Notes.',
    'helperRecords tipe state-transition dengan row editable/delete.',
    '1. Internal Helpers → State Transition Builder.\n2. + Add Row.\n3. Isi state dan authority transisi.\n4. Simpan dan jadikan rujukan test.',
    'active → revoked; action Owner mencabut Member; invariant Member tidak menerima export baru sesudah revoke efektif.',
    'Memberi bahan untuk Hypotheses/Tests dan mapping lifecycle manual.',
    'Partial: row manual, bukan graph/state machine yang dieksekusi. Tidak mengubah object state target atau coverage secara otomatis.', status='Partial', helper='state-transition')

add('helper-trust-boundary', 'Trust Boundary Mapper',
    'Membuka modul Trust Boundaries untuk mencatat perpindahan trust/authority.',
    'Menggunakan satu tempat penyimpanan boundary agar mapping tetap konsisten.',
    'Ketika helper diperlukan untuk mapping komponen.',
    'Pada modul tujuan: From/To, Channel, Trust, Authority, Notes.',
    'Navigasi ke Trust Boundaries; row tersimpan setelah Anda mengisi dan Save di sana.',
    '1. Internal Helpers → Trust Boundary Mapper.\n2. Open Trust Boundaries.\n3. Tambah/edit row seperti dijelaskan pada Trust Boundaries.',
    'API → Worker export Example SaaS dengan revalidation membership terbaru.',
    'Memakai Boundaries yang sama dengan Attack Surface/Tests/Coverage.',
    'Ini shortcut modul, bukan generator graph atau mapping otomatis.', helper='trust-boundary')

add('helper-evidence-comparator', 'Evidence Comparator',
    'Membandingkan keberadaan baris unik pada dua teks evidence lokal.',
    'Membantu melihat perbedaan respons kontrol dan percobaan tanpa mengirim data ke AI.',
    'Sesudah merekam dua observasi yang dapat dibandingkan.',
    'Evidence A/B yang ditempel atau content dari evidence tersimpan pilihan.',
    'Preview baris sama, − hanya A, + hanya B; hasil tidak otomatis disimpan.',
    '1. Pilih Evidence Comparator.\n2. Tempel A/B atau pilih stored evidence.\n3. Compare Evidence.\n4. Catat perbedaan bermakna dalam test/notes.',
    'Bandingkan respons Member aktif versus revoked untuk marker Export Demo.',
    'Membaca content Evidence; peneliti menyalin hasil relevan ke Test/Finding/Notes.',
    'Partial: bukan diff yang mempertahankan urutan atau jumlah duplikasi baris, bukan JSON structural/semantic comparator. Preview hilang ketika pindah view.', status='Partial', helper='evidence-comparator')

add('helper-secret-redactor', 'Secret Redactor',
    'Preview redaksi pola kredensial, header sensitif, JWT, dan email pada teks.',
    'Mengurangi data sensitif pada evidence, note, report, atau context AI yang Anda review.',
    'Sebelum menyimpan/membagikan evidence atau mengirim context cloud.',
    'Teks mentah pada Text to redact. Pola mencakup Authorization/Proxy-Authorization, Bearer, Cookie/Set-Cookie, API Key, JWT, session ID/token, password, access/refresh token, CSRF/XSRF token, beberapa key prefixes dan email.',
    'Redacted preview; Save Redacted Note menyimpan output preview sebagai note, bukan mengganti evidence.',
    '1. Pilih Secret Redactor.\n2. Paste teks → Redact Preview.\n3. Review manual semua bagian.\n4. Salin hasil ke evidence atau Save Redacted Note.',
    'Authorization: Bearer token-dummy menjadi Authorization: [REDACTED]; label dummy SECRET_ACCOUNT_A_123 dapat tetap ada jika tidak cocok pola secret.',
    'AI privacy memakai redactor yang sama secara otomatis pada mode/flag yang mensyaratkannya; Notes menerima Save output; evidence manual perlu Anda ubah sendiri.',
    'Partial: redaksi berbasis pola tidak mengenali seluruh secret/PII dan bukan enkripsi. Raw input hanya berada di form helper, bukan disimpan helper; output baru disimpan bila memilih Save. Metadata/teks naratif dapat tetap sensitif.', status='Partial', helper='secret-redactor')

add('helper-hypothesis-generator', 'Hypothesis Generator — Offline Template',
    'Membuka editor hypothesis yang diprefill dari teknik tanpa AI.',
    'Mempercepat penulisan dugaan sambil mempertahankan review peneliti.',
    'Sesudah memilih technique dan sebelum test.',
    'Technique for hypothesis dari daftar target.',
    'Editor dengan judul, techniqueId, invariant, potential failure dan notes template; record dibuat hanya saat Simpan.',
    '1. Pilih Hypothesis Generator di Internal Helpers.\n2. Pilih technique.\n3. Preview / Edit Hypothesis.\n4. Lengkapi formula/expected behavior.\n5. Simpan atau Batal.',
    'Pilih Async Authorization untuk draft invariant worker mengecek authority pada execution.',
    'Membaca Technique Library dan membuat Hypotheses; berbeda dari Operation AI generate_hypotheses.',
    'Template bukan analisis target. Review relevansi invariant/stop conditions, walaupun teks awal sudah terisi.', helper='hypothesis-generator')

add('helper-scope-checker', 'Scope Checker',
    'Menampilkan assessment dan restrictions dari scope/guard/rules yang dicatat.',
    'Membantu melihat data izin yang masih kurang sebelum meminta rekomendasi.',
    'Sebelum Tool Knowledge/AI atau ketika rules berubah.',
    'Target asset, In/Out of Scope, tiga guard awal, flags rules, testing/automation restrictions.',
    'Status assessment, alasan, daftar restrictions, dan tombol Edit Scope & Rules.',
    '1. Pilih Scope Checker.\n2. Baca status/alasan.\n3. Edit Scope & Rules untuk memperbaiki catatan.\n4. Review izin aktual secara manual.',
    'Tanpa konfirmasi data owned, Example SaaS menunjukkan requires_manual_review.',
    'Menggunakan rules service yang sama dengan offline tool recommendations dan backend AI.',
    'Tidak memindai asset, mengambil rules program, atau mengevaluasi wildcard/path. within_supplied_scope hanya kesesuaian catatan manual; lihat batasan Rules Engine.', helper='scope-checker')

add('helper-finding-checklist', 'Finding Checklist',
    'Checklist kelengkapan delapan unsur finding dan evidence.',
    'Menunjukkan informasi dasar yang belum disediakan sebelum review/report.',
    'Sesudah promotion dan sebelum membuat report.',
    'Finding pilihan; Expected, Actual, Starting Authority, Protected Resource, Security Restriction, Steps, Evidence attached, Impact.',
    'Tanda ada/belum ada pada delapan unsur berdasarkan isi field/evidenceIds.',
    '1. Pilih Finding Checklist.\n2. Pilih finding.\n3. Periksa item kosong.\n4. Edit finding/attach evidence lalu review ulang.',
    'Finding export tanpa starting authority menunjukkan item tersebut belum lengkap.',
    'Membaca Findings; peneliti memperbaiki Findings/Evidence sebelum Reports.',
    'Checklist kelengkapan, bukan false-positive validator, severity estimator, atau bukti validity. Semua centang dapat muncul walau isi field masih salah.', helper='finding-checklist')

add('helper-duplicate-comparator', 'Duplicate Comparator',
    'Membandingkan kemiripan teks lima unsur finding dengan kandidat lokal/manual.',
    'Memberi petunjuk risiko issue sama sambil menampilkan ketidakpastian.',
    'Sesudah finding cukup terisi dan sebelum laporan/submission manual.',
    'Finding sumber; kandidat finding lain target aktif, KB Disclosed Reports/Finding Patterns/False Positives, atau manual; Root Cause, Security Boundary, Primitive/Class, Component, Impact.',
    'Likely Unique/Possible Variant/Likely Duplicate/Unknown, score text similarity %, dan catatan keterbatasan.',
    '1. Pilih Duplicate Comparator dan finding.\n2. Pilih kandidat atau isi lima field.\n3. Compare Duplicate Risk.\n4. Review kesamaan root cause/boundary secara manual.',
    'Bandingkan export-worker revalidation Example SaaS dengan disclosed report dummy tentang job yang memakai izin lama.',
    'Membaca Findings/KB target aktif; Known Issues hanya memprefill root cause kandidat manual; tidak mengubah finding status.',
    'Partial: Jaccard kata >2 karakter per field, rata-rata field berisi pada kedua sisi. Kurang dari dua field → Unknown; ≥80% Likely Duplicate; ≥35% Possible Variant; lainnya Likely Unique. Bukan keputusan program, pencarian internet, embedding, atau pembandingan semua target. Nilai mirip rendah tidak membuktikan unik.', status='Partial', helper='duplicate-comparator')

add('helper-report-builder', 'Report Builder',
    'Membuka Reports untuk menyusun laporan Indonesia dari finding.',
    'Memberi akses langsung dari helper workflow ke generator deterministik.',
    'Sesudah finding dan evidence direview.',
    'Finding target aktif dipilih pada halaman Reports.',
    'Navigasi Reports; draft/export dihasilkan lewat controls Reports.',
    '1. Pilih Report Builder.\n2. Open Indonesian Reports.\n3. Pilih finding, Generate Report, review/edit dan export.',
    'Buat report dummy export Example SaaS dengan impact sesuai observasi.',
    'Shortcut ke Report Generator yang sama; tidak membuat template atau penyimpanan terpisah.',
    'Membuka helper tidak langsung menyimpan draft. Periksa redaksi evidence dan field kosong sebelum export.', helper='report-builder')

add('helper-gap-analyzer', 'Research Gap Analyzer — Helper',
    'Menampilkan panel coverage dan lifecycle/surface gaps lokal.',
    'Membantu mencari catatan pengujian berikutnya dari entri yang belum tercakup.',
    'Setelah mencatat beberapa test atau sebelum sesi berikutnya.',
    'Technique enabled, actors, objects, states, boundaries, test results target aktif.',
    'Panel rasio dan Untested serta pesan heuristic yang sama dengan Research Gaps.',
    '1. Pilih Research Gap Analyzer.\n2. Baca Untested dan Lifecycle & Surface Gaps.\n3. Cocokkan dengan scope/risiko.\n4. Buat hypothesis/test manual.',
    'Owner belum muncul di test Example SaaS; pilih kontrol Owner bila relevan.',
    'Memakai Coverage service yang sama, berbeda dari AI Gap Analyzer.',
    'Partial: menghitung catatan, bukan seluruh kombinasi atau inspeksi evidence. Missing revocation/async/cross-surface memakai kata technique/state.', status='Partial', helper='gap-analyzer')

add('coverage', 'Research Gaps dan Research Coverage',
    'Rasio dan daftar actor/object/state/boundary/technique yang belum mempunyai hasil test.',
    'Mengubah backlog riset menjadi prioritas berbasis catatan yang tersedia.',
    'Setelah test dan saat merencanakan sesi berikutnya.',
    'Test dengan result nonempty selain not-tested; techniques enabled; actor/object names; state unik dari objects+hypotheses+tests; boundary IDs.',
    'Covered / total, Untested per lima dimensi; missing revocation/async/cross-surface heuristic. Tidak ada persen category Authorization/Async/OAuth atau grafik lengkap kombinasi.',
    '1. Research Gaps → baca lima panel.\n2. Periksa ejaan snapshot dan boundary selection bila rasio mengejutkan.\n3. Pilih gap relevan dengan scope.\n4. Buat hypothesis/test.\n5. Catat hasil untuk memperbarui rasio.',
    'Actor 1 / 2: Member mempunyai hasil test, Owner belum. Boundary 0 / 1 tetap nol jika test tidak memilih boundary walau context menyebut API → Worker.',
    'Dashboard dan helper Gap Analyzer memakai perhitungan sama; AI Gap Analyzer memberi saran draft tambahan.',
    'Partial: PASS/FAIL/INCONCLUSIVE/VULNERABILITY semua dihitung sebagai tercatat, bukan aman. Actor/object/state teks harus cocok persis; teknik/boundary lewat ID. 0 / 0 berarti belum dipetakan, bukan complete. Pesan lifecycle membaca kata nama technique + test.state, bukan langkah/evidence; tidak mengukur setiap kombinasi.', status='Partial', routes=['coverage'])

add('research-priority', 'Research Priority',
    'Skor prioritas riset 0–100 dan urutan teknik untuk membantu menentukan tindak lanjut.',
    'Mempertimbangkan nilai pembelajaran, biaya, scope, bukti dan duplicate risk.',
    'Saat memilih technique atau membaca rekomendasi AI.',
    'Technique editor: manual researchPriority/duplicateRisk/testingCost 0–100. AI: potentialImpact, likelihood, novelty, testingCost, duplicateRisk, scopeConfidence, evidenceQuality masing-masing 0–100.',
    'Skor dan reason dalam structured AI result; sorting technique memakai skor manual. Hypothesis priority high/medium/low adalah field terpisah.',
    '1. Tentukan skor manual technique jika berguna.\n2. Gunakan sorting priority/risk/cost.\n3. Jika AI aktif, baca score beserta alasan dan quality context.\n4. Putuskan next step manual.',
    'Dugaan export-worker dapat diprioritaskan setelah evidence timing membaik, walau severity finding masih Unknown.',
    'Technique Library, Hypotheses dan AI Results memiliki bentuk prioritas berbeda; severity berada pada Findings.',
    'Research Priority bukan Vulnerability Severity. AI score dihitung ulang sebagai round((impact + likelihood + novelty + (100-cost) + (100-duplicateRisk) + scopeConfidence + evidenceQuality) / 7); input tetap estimasi AI. Score tidak otomatis menulis skor technique atau P1–P5.')

add('settings', 'Settings dan System Health',
    'Ringkasan storage/autosave/schema/AI dan akses konfigurasi serta backup.',
    'Membantu melihat apakah catatan tersimpan dan backend opsional siap.',
    'Saat startup, storage error, konfigurasi AI, atau sebelum backup.',
    'Status storage/persistence, safe backend config, Backend localhost origin; actions backup/file/reset.',
    'Storage IndexedDB OK/Error; Autosave Active/Pending; schema; AI status; privacy mode; provider/model. Settings, AI Provider, Backup berbagi tampilan panel yang sama.',
    '1. Buka Settings.\n2. Periksa storage/autosave.\n3. Periksa AI atau Connect Backend bila diperlukan.\n4. Gunakan backup jika ada error penyimpanan.',
    'AI Disabled pada Example SaaS tetap memungkinkan report manual dan export.',
    'Mengambil status storage dan AI bridge, serta controls Backup/Reset/Optional file.',
    'System Health bukan monitoring uptime/model atau koneksi provider live. IndexedDB OK mengikuti status pembacaan/penulisan aplikasi terakhir; indikator header menunjukkan status save lebih langsung.', routes=['settings'])

add('ai-provider', 'AI Configuration dan Connection',
    'Menghubungkan frontend ke backend lokal dengan provider/model yang dikonfigurasi server.',
    'Mempertahankan workflow manual sekaligus memberi opsi AI tanpa menaruh key di browser.',
    'Sebelum meminta AI atau ketika mengganti provider/model.',
    'Server .env: AI_ENABLED; AI_PROVIDER openai/anthropic/gemini/ollama; OPENAI_MODEL+OPENAI_API_KEY, ANTHROPIC_MODEL+ANTHROPIC_API_KEY, GEMINI_MODEL+GEMINI_API_KEY, atau OLLAMA_MODEL+OLLAMA_BASE_URL; AI_PRIVACY_MODE; AI_REDACT_SECRETS; SERVER_HOST/PORT.',
    'Safe config tanpa API key; status Disabled/Misconfigured/Connected/Provider Error dan token request session internal.',
    '1. Review .env.example, edit .env server.\n2. AI_ENABLED=false untuk manual; true + model/key untuk cloud, atau model/server Ollama lokal.\n3. Restart backend.\n4. Buka URL backend atau AI Provider → Connect Backend dengan origin localhost.\n5. Coba context dummy untuk memeriksa request.',
    'AI_PROVIDER=ollama; OLLAMA_BASE_URL=http://127.0.0.1:11434; OLLAMA_MODEL nama model terpasang; LOCAL_ONLY. Tidak ada model bawaan/default.',
    'AI modules menggunakan bridge ini. Backend halaman utama otomatis menghubungkan safe config; mode file:// tetap manual karena Origin null ditolak.',
    'AI_ENABLED=true belum cukup tanpa config valid. Disabled tidak menginisialisasi provider. Connected awal berarti config siap, bukan key/model sudah teruji. Backend loopback; Connect Backend bukan URL asset target. Key hanya di .env server; jangan masukkan ke Notes/Evidence/AI goal. Provider nyata memerlukan layanan/model dan kemampuan structured output yang kompatibel.', routes=['ai-provider'])

add('ai-privacy', 'AI Privacy Modes dan Context Preview',
    'Mengatur provider lokal/cloud, redaksi pola, dan persetujuan payload sebelum request.',
    'Membuat peneliti melihat data yang akan meninggalkan browser.',
    'Sebelum setiap request AI, terutama evidence/finding/report sensitif.',
    'LOCAL_ONLY/REDACTED_CLOUD/CLOUD; server AI_REDACT_SECRETS; target aktif; goal/notes, technique/finding pilihan, evidence/KB opt-in.',
    'Preview JSON; allowlist context; request hanya setelah Send for Analysis. LOCAL_ONLY hanya Ollama loopback; REDACTED_CLOUD selalu redaksi; CLOUD masih redaksi jika flag server true.',
    '1. Pilih mode pada form AI.\n2. Centang evidence/KB hanya bila perlu.\n3. Preview AI Context dan baca seluruh payload.\n4. Batalkan/perbaiki jika belum aman.\n5. Send for Analysis.',
    'Untuk finding Example SaaS, evidence opt-in membawa teks/description/type/label dari evidence terkait finding; path file tidak dikirim.',
    'Context builder membaca target aktif saja, termasuk profil/scope/actors/objects/boundaries/enabled techniques/hypotheses/tests/finding summaries/selected finding; request/response notes test hanya bila evidence opt-in. Report Assistant membawa report draft. Redactor berjalan frontend dan backend jika diwajibkan.',
    'Evidence/KB opt-in default off, tetapi actual/expected, selected finding research notes, arsitektur dan goal tetap bisa sensitif. REDACTED_CLOUD bukan anonymization sempurna. CLOUD + AI_REDACT_SECRETS=false bisa mengirim raw context. API keys tidak dimasukkan context. Config/token bridge hanya memory session; research/suggestions tetap autosave lokal.')

add('ai', 'Research Assistant',
    'Saran terstruktur tentang riset target berdasarkan context yang direview peneliti.',
    'Membantu merumuskan pertanyaan, missing context dan langkah aman tanpa eksekusi pengujian.',
    'Sesudah target/scope/mapping terisi atau ketika arah riset belum jelas.',
    'Operation research_advice; target aktif/scope/rules/mapping/riset; goal/notes; technique/finding opsional; privacy mode dan evidence/KB opt-in.',
    'Structured JSON scope assessment/rules, recommendations, safe next steps/avoid/stop/missing context, confidence 0–1, questions/hypotheses/finding analysis/research priority/gaps/report draft; field tidak relevan dapat kosong.',
    '1. Research Assistant → pilih Operation Research Assistant.\n2. Isi goal/context.\n3. Preview → Send.\n4. Baca structured result.\n5. Reject atau Accept/Edit Note; review hypothesis/report terpisah.',
    'Goal Example SaaS: menilai kapan worker perlu revalidate permission export setelah revoke.',
    'Satu form melayani 15 operasi. Lima menu AI memberi pilihan awal; pilihan Operation terakhir dapat tetap tersimpan selama session. Tiap operasi memiliki entri berikut.',
    'Tidak ada command terpisah Analyze Target; gunakan research_advice. AI disabled/misconfigured menampilkan petunjuk konfigurasi. Schema JSON divalidasi sebelum suggestion disimpan pending; tidak ada auto confirm/severity/execution. Pengujian provider nyata bergantung konfigurasi Anda.', routes=['ai'], operation='research_advice')

add('ai-analyze-scope', 'AI Analyze Scope',
    'Saran review scope dan konteks izin berdasarkan catatan yang supplied.',
    'Mengidentifikasi informasi scope/rules yang masih kurang sebelum menyusun test.',
    'Sesudah mengisi Scope dan ketika ketentuan belum jelas.',
    'Operation analyze_scope; profil target, scope/guard/rules, research goal/notes.',
    'Scope assessment dari hard policy, rules, missingContext, pertanyaan dan saran review.',
    '1. Research Assistant → Analyze Scope.\n2. Isi pertanyaan batas izin.\n3. Preview → Send.\n4. Perbaiki Scope/Guard sendiri dari hasil review.',
    'Tanyakan informasi yang kurang untuk memastikan export-worker Example SaaS termasuk scope laboratorium.',
    'Rules Engine menetapkan assessment final; AI tidak mengubah scope atau flags.',
    'Tidak mengambil halaman program atau memastikan izin secara independen. Assessment supplied scope memakai batasan Scope Checker yang sama.', operation='analyze_scope')

add('ai-techniques', 'AI Technique Advisor',
    'Meranking teknik enabled yang tersedia berdasarkan context dan hard policy.',
    'Membantu memilih invariant relevan tanpa menciptakan teknik di luar katalog target.',
    'Sesudah mapping atau saat memilih prioritas baru.',
    'Operation recommend_techniques; enabled techniques, target/scope/actors/objects/boundaries/goal dan context riset.',
    'recommendedTechniques: name, priority 0–100, reason, securityInvariant; researchPriority umum dan missing context.',
    '1. Technique Advisor atau pilih Operation di form AI.\n2. Isi goal.\n3. Preview → Send.\n4. Review alasan dan pilih teknik manual di library.',
    'Async Authorization dipertimbangkan karena Example SaaS memakai worker dengan perubahan membership.',
    'Teknik kandidat dari Technique Library target aktif; dapat dilanjutkan ke Hypothesis Generator atau manual hypothesis.',
    'AI tidak otomatis mengaktifkan/mengubah skor technique. Jika AI mati, seluruh library/filter/sorting/manual selection tetap tersedia. Scope yang belum memadai membatasi rekomendasi.', routes=['ai-techniques'], operation='recommend_techniques')

add('ai-tools', 'AI Tool Advisor',
    'Saran tools manual dari Tool KB yang sudah difilter policy dan technique relevance.',
    'Menghubungkan pertanyaan pengujian dengan alat observasi yang sesuai.',
    'Sesudah memilih technique dan sebelum menyiapkan test manual.',
    'Operation recommend_tools; technique context, target/scope/rules/mapping/goal. Backend membangun kandidat domain/tag dari teknik.',
    'toolSuggestions dengan id/name/category/purpose/usageMode manual/whyUseful/scopeWarning; tool di luar kandidat dihapus.',
    '1. Tool Advisor → pilih technique context.\n2. Jelaskan tujuan observasi.\n3. Preview → Send.\n4. Review mode manual/rules.\n5. Gunakan tool eksternal sendiri bila dibolehkan.',
    'Technique IDOR/BOLA → Burp Repeater sebagai replay manual → Authorization Matrix Builder sebagai helper internal.',
    'Tool KB + Rules Engine → kandidat → AI ranking → filter output. Offline Tool Knowledge tetap tersedia tanpa AI.',
    'Relevance adalah domain/tag dan context supplied, bukan hasil discovery target. Tidak ada install/execute command. Tool yang punya automation tidak berarti seluruh kemampuan tersebut diizinkan.', routes=['ai-tools'], operation='recommend_tools')

add('ai-helper-advisor', 'AI Helper Advisor',
    'Merekomendasikan helper internal dari katalog yang sudah tersedia.',
    'Mengarahkan peneliti ke fitur pencatatan atau review yang sesuai kebutuhan.',
    'Saat mapping, evidence preparation, atau review finding.',
    'Operation recommend_helpers; target/mapping/research goal dan context.',
    'helperSuggestions id/name/purpose yang harus cocok katalog internal.',
    '1. Research Assistant → Helper Advisor.\n2. Isi kebutuhan.\n3. Preview → Send.\n4. Buka Internal Helpers dan pilih nama yang disarankan sendiri.',
    'State Transition Builder untuk active → revoked; Finding Checklist sebelum laporan export.',
    'HELPER_KB membatasi nama; helper lokal menyediakan action sebenarnya.',
    'Rekomendasi tidak menjalankan helper atau otomatis menyimpan row. Helper tetap dapat dipilih manual saat AI disabled.', operation='recommend_helpers')

add('ai-questions', 'AI Research Questions',
    'Menghasilkan pertanyaan riset dari mapping, invariant, dan missing context.',
    'Membantu mengurai ketidakjelasan sebelum mengubahnya menjadi hypothesis.',
    'Saat mapping awal atau hasil test masih inconclusive.',
    'Operation research_questions; target/scope/mapping/riset, goal/notes.',
    'researchQuestions dan missingContext serta struktur umum AI.',
    '1. Pilih Research Questions.\n2. Jelaskan ketidakjelasan.\n3. Preview → Send.\n4. Simpan pertanyaan relevan sebagai note/hypothesis manual.',
    'Apakah worker Example SaaS mengecek membership saat enqueue atau execution?',
    'Pertanyaan dapat mengarah ke Hypotheses/Test Cases/KB setelah peneliti mereview.',
    'Pertanyaan bukan bukti kegagalan dan tidak otomatis menjadi test atau checklist.', operation='research_questions')

add('ai-hypothesis-generator', 'AI Hypothesis Generator',
    'Menghasilkan draft hypothesis dari context dan technique kandidat.',
    'Mempercepat ide pengujian yang tetap harus disesuaikan dengan scope dan fakta.',
    'Sesudah mapping/technique selection dan sebelum test.',
    'Operation generate_hypotheses; goal/mapping, teknik enabled atau pilihan, scope/rules dan riwayat riset.',
    'Draft title/technique/invariant/expectedBehavior/potentialFailure/enam dimensi; tombol Review Hypothesis membuka editor.',
    '1. Pilih Hypothesis Generator pada form AI.\n2. Preview → Send.\n3. Review Hypothesis.\n4. Perbaiki field, simpan atau batal.\n5. Buat test sendiri.',
    'Draft Member revoked tidak memperoleh export worker Example SaaS dengan confidence awal low dan status idea pada editor.',
    'Menerima context/techniques; editor membuat Hypotheses setelah Simpan. Offline helper memakai template tanpa AI.',
    'Menyimpan satu hypothesis tidak menandai batch suggestion accepted; status batch tetap pending sampai note/report diterima atau Reject. AI tidak menambah hypothesis sebelum persetujuan editor.', operation='generate_hypotheses')

add('ai-findings', 'AI Finding Analyzer',
    'Saran analisis invariant, class, root cause, impact, missing evidence dan safe validation.',
    'Membantu mereview kelemahan argumen finding sebelum menyimpulkan atau melapor.',
    'Sesudah finding draft dan evidence disiapkan.',
    'Operation analyze_finding; Finding context wajib; facts/formula/evidence metadata/text opt-in, related research dan goal.',
    'findingAnalysis: assessment, potentialClass, brokenInvariant, potentialRootCause, falsePositiveChecks, missingEvidence, potentialImpact, duplicateRisk, safeValidation; priority/confidence umum.',
    '1. Finding Analyzer → pilih Finding context.\n2. Sertakan evidence hanya jika sudah aman dan perlu.\n3. Preview → Send.\n4. Review saran dan validasi manual yang diizinkan.\n5. Edit finding sendiri jika bukti mendukung.',
    'AI dapat menduga worker memakai izin enqueue; peneliti tetap harus membuktikan waktu/revalidation pada Example SaaS.',
    'Membaca selected finding dan context target aktif; tidak menulis facts/status/severity. Saran bisa disimpan sebagai note.',
    'Observed berarti fakta yang tercatat; Confirmed berarti kesimpulan yang sudah diverifikasi peneliti; Hypothesis berarti dugaan; Unknown berarti belum cukup data. Walau schema memuat empat label, backend saat ini memaksa generated finding assessment menjadi Hypothesis jika finding dipilih, atau Unknown jika tidak ada finding. AI tidak mengeluarkan konfirmasi otomatis.', routes=['ai-findings'], operation='analyze_finding')

add('ai-false-positive', 'AI False Positive Analyzer',
    'Mengusulkan alasan perilaku mungkin sah dan kontrol pembanding yang masih diperlukan.',
    'Menguji penjelasan alternatif sebelum menganggap observasi sebagai vulnerability.',
    'Sesudah finding draft dan sebelum confirmation/report.',
    'Operation false_positive_analysis; Finding context wajib; expected/actual/authority/ownership/context, goal/notes dan evidence opt-in.',
    'falsePositiveChecks, missingEvidence, safeValidation dan assessment Hypothesis pada finding analysis.',
    '1. Pilih False Positive Analyzer dan finding.\n2. Jelaskan role/ownership/timing.\n3. Preview → Send.\n4. Verifikasi checks manual dan catat hasilnya.',
    'Periksa documented behavior, shared/public object, eventual consistency, supported role capability, atau capability export yang masih berlaku.',
    'Membaca Findings/Evidence/context; hasil menjadi note dan rencana kontrol Test Cases.',
    'Partial: menghasilkan pertanyaan/draft, tidak men-fetch dokumentasi program atau menjalankan kontrol untuk membuktikan false positive. Finding Checklist offline memeriksa kelengkapan, bukan validitas.', status='Partial', operation='false_positive_analysis')

add('ai-duplicate', 'AI Duplicate Analyzer',
    'Estimasi duplicate dari finding dan pembanding dalam context yang supplied.',
    'Membantu meninjau kesamaan akar masalah dengan issue yang diketahui.',
    'Sesudah finding dan known issues/KB pembanding tersedia.',
    'Operation duplicate_analysis; Finding context wajib; known issues, ringkasan finding target aktif, KB opt-in dengan rootCause/boundary/class/component/impact.',
    'duplicateRisk Likely Unique/Possible Variant/Likely Duplicate/Unknown dalam findingAnalysis, confidence/missing context dan saran review.',
    '1. Masukkan Known Issues/KB pembanding.\n2. Pilih Duplicate Analyzer dan finding.\n3. Centang KB jika relevan.\n4. Preview → Send.\n5. Review persamaan lima unsur secara manual.',
    'Bandingkan stale worker authority Example SaaS dengan report dummy yang memiliki root cause dan protected boundary sama.',
    'Membaca context lokal supplied; berbeda dari helper Duplicate Comparator yang menghitung text similarity deterministik.',
    'Partial: tidak mencari seluruh internet/disclosed reports/target lain atau memutuskan duplicate program. Output adalah estimasi AI, bukan ambang similarity helper. Pembanding kosong seharusnya dinilai Unknown, bukan bukti unik.', status='Partial', operation='duplicate_analysis')

add('ai-gaps', 'AI Gap Analyzer',
    'Saran gap riset dari mapping dan test yang supplied ke model.',
    'Membantu menanyakan actor/object/state/boundary atau lifecycle yang belum jelas.',
    'Saat merencanakan sesi baru setelah mencatat hasil test.',
    'Operation gap_analysis; actor/object/boundary/technique/hypothesis/test context, goal/notes.',
    'gapAnalysis, researchQuestions, safeNextSteps dan priority draft.',
    '1. AI Gap Analyzer → pilih Operation yang benar.\n2. Preview → Send.\n3. Bandingkan saran dengan Research Gaps lokal.\n4. Buat hypothesis/test yang relevan.',
    'AI menyarankan membedakan execution worker dan download result setelah revoke pada Example SaaS.',
    'Membaca context riset; tidak mengubah coverage lokal atau otomatis membuat test.',
    'AI suggestions bukan score coverage atau bukti semua kombinasi sudah diuji. Gunakan rasio lokal untuk catatan tercatat dan review semantic manual.', routes=['ai-gaps'], operation='gap_analysis')

add('ai-report-assistant', 'AI Report Assistant',
    'Draft perbaikan report yang dipreview dan diedit sebelum mengganti Markdown tersimpan.',
    'Membantu kejelasan tulisan tanpa mengubah keputusan faktual peneliti secara otomatis.',
    'Sesudah report awal dan finding/evidence direview.',
    'Operation improve_report; Finding context wajib; reportMarkdown saat ini atau template jika belum ada; facts dan evidence opt-in.',
    'reportDraft, tombol Preview / Edit Report Draft; Save memperbarui reportMarkdown sumber dan menandai suggestion accepted.',
    '1. Pilih Report Assistant dan finding.\n2. Preview context termasuk draft.\n3. Send → baca reportDraft.\n4. Preview / Edit Report Draft.\n5. Pastikan fakta/severity tidak berubah; Simpan atau Batal.',
    'Perbaiki alur penjelasan enqueue/revoke/execute pada laporan Example SaaS sambil mempertahankan severity Unknown.',
    'Membaca Findings/Reports; acceptance hanya mengganti Markdown, bukan fields fakta/status/severity finding.',
    'Model tetap dapat mengarang narasi meskipun prompt melarangnya; review setiap klaim. Bila finding sumber sudah dihapus, draft tidak dapat diterapkan ke finding tersebut.', operation='improve_report')

add('ai-evidence-summary', 'AI Evidence Summarizer',
    'Ringkasan/analisis evidence yang disertakan melalui context opt-in.',
    'Membantu merangkum observasi panjang menjadi note yang bisa direview.',
    'Sesudah evidence redacted dan sebelum analisis/report.',
    'Operation evidence_summary; Include evidence text, finding opsional, goal dan teks evidence terkait/seluruh target sesuai pilihan.',
    'Saran naratif dalam structured result, terutama findingAnalysis/safeNextSteps/missingContext bila relevan. Tidak ada field terpisah evidenceSummary atau artifact ringkasan otomatis.',
    '1. Pilih Evidence Summarizer.\n2. Centang evidence dan pilih finding jika ingin membatasi relasi.\n3. Preview seluruh teks.\n4. Send; review lalu simpan note yang relevan.',
    'Ringkas log timing export dummy Example SaaS tanpa memasukkan token session.',
    'Membaca Evidence text; Accept/Edit Note menyimpan ringkasan pilihan peneliti ke Notes.',
    'Bukan pembaca screenshot/video/path binary atau parser HAR. Jika evidence opt-in off, model tidak menerima evidence text. Output selalu memakai schema umum, bisa tidak mengisi bagian tertentu.', operation='evidence_summary')

add('ai-safe-next-steps', 'AI Safe Next Steps',
    'Draft tindakan tindak lanjut yang dibatasi scope/rules dan stop conditions.',
    'Membantu memperjelas langkah review berikutnya tanpa eksekusi target.',
    'Ketika hasil inconclusive atau missing evidence masih ada.',
    'Operation safe_next_steps; scope/rules, goal, test/finding context yang relevan.',
    'safeNextSteps, avoid, stopConditions dan missingContext.',
    '1. Pilih Safe Next Steps.\n2. Jelaskan hambatan.\n3. Preview → Send.\n4. Review izin aktual sebelum mengubah rencana manual.',
    'Lengkapi bukti revoke efektif pada laboratorium Example SaaS sebelum mengulang satu test terkontrol.',
    'Rules filter membatasi saran; peneliti memperbarui Notes/Hypotheses/Tests manual.',
    'Nama safe bukan jaminan seluruh saran valid. Jika scope belum lengkap, backend mengganti next steps dengan permintaan melengkapi scope/izin/data.', operation='safe_next_steps')

add('ai-restrictions', 'AI Restrictions',
    'Saran review pembatasan dari program rules dan scope yang dicatat.',
    'Membantu memeriksa batas yang mungkin terlupakan ketika menyusun test.',
    'Sebelum test dan setiap rules/arsitektur berubah.',
    'Operation identify_restrictions; scope testing/automation rules, flags, rate limits, safe harbor dan research goal.',
    'rules final dari policy, avoid, stopConditions, missing context dan saran review.',
    '1. Pilih Restrictions.\n2. Isi tujuan pengujian.\n3. Preview → Send.\n4. Cocokkan dengan ketentuan asli dan perbarui Scope sendiri.',
    'Example SaaS: manual only, no third-party testing, stop jika data bukan milik peneliti.',
    'Rules Engine mempertahankan prioritas program rules; tidak mengubah flags.',
    'Tidak menafsirkan izin hukum absolut atau mengambil ketentuan terbaru dari Program URL. Output rules yang authoritative berasal dari catatan policy, bukan izin yang diciptakan AI.', operation='identify_restrictions')

add('ai-review', 'AI Suggestions — Preview, Accept, Edit, Reject',
    'Review eksplisit suggestion pending sebelum diterapkan sebagai note, hypothesis, atau report.',
    'Memisahkan draft model dari keputusan dan fakta yang disimpan peneliti.',
    'Sesudah setiap request AI yang berhasil.',
    'Output JSON valid, operation/sourceFindingId/provider/privacy/timestamp; keputusan peneliti dan edit content.',
    'Suggestion pending/accepted/rejected; Notes hasil Accept/Edit; Hypotheses setelah editor Save; reportMarkdown setelah Review Report Save; suggestion dapat dihapus.',
    '1. Baca structured preview/status/priority/confidence.\n2. Reject bila tidak relevan.\n3. Accept as Research Note atau Edit / Accept Note bila ingin menyimpan.\n4. Review Hypothesis untuk membuat record yang diperiksa.\n5. Preview/Edit Report Draft untuk menerapkan draft ke finding sumber.',
    'AI draft tentang izin worker Example SaaS belum mengubah hypothesis/finding; peneliti melengkapi invariant/formula di editor lalu Simpan.',
    'Schema validator frontend/backend memvalidasi data; storage menyimpan suggestion; Notes/Hypotheses/Reports menerima hasil yang disetujui.',
    'Accept Note menandai batch accepted, bukan membuktikan rekomendasi benar. Review Hypothesis Save tidak menandai batch accepted. Tidak ada auto update facts/severity/rules/confirmed. Error provider/JSON menghasilkan pesan dan workflow manual tetap tersedia.')

add('search', 'Global Search dan List Filters',
    'Pencarian lintas target dan domain untuk research, profil bisnis, terminology, business flows, invariants, failure patterns, related techniques, KB dan lessons.',
    'Menemukan catatan lama dan menyempitkan review tanpa mengganti data.',
    'Ketika jumlah catatan bertambah atau mencari observasi tertentu.',
    'Global query teks; filter target hasil; query/status/technique/actor/object/severity/category sesuai daftar modul.',
    'Tombol hasil dengan nama target/jenis/status; navigasi target dan modul hasil; daftar modul yang difilter.',
    '1. Ketik pada search global di header.\n2. Pilih target filter jika perlu.\n3. Klik hasil untuk berpindah target/modul.\n4. Gunakan search/filter lokal untuk menyempitkan daftar.\n5. Kosongkan search untuk kembali.',
    'Cari revoke untuk menemukan hypothesis dan test Example SaaS lintas target; filter finding berdasarkan Unknown atau P1–P5.',
    'Membaca research dan KB seluruh workspace serta curated/custom domain packs; relasi flow menghubungkan hasil glossary dengan invariant dan technique mapping.',
    'Global Search dibatasi 200 hasil; evidence mentah, actors dan objects tidak diindeks sebagai koleksi mandiri. Hasil menuju modul, tanpa highlight/deep link record tertentu. Query daftar lokal diterapkan saat change, misalnya Enter/blur; filter bisa tetap tersimpan selama target belum berubah.')

add('workspace-storage', 'Workspace Storage dan Autosave',
    'IndexedDB sebagai autosave utama, journal recovery opsional, dan JSON portabel schema v2.',
    'Mempertahankan catatan lokal serta mendukung recovery/migrasi dan perpindahan origin.',
    'Otomatis ketika mengubah data; export sebelum pindah browser/origin.',
    'Seluruh target/koleksi riset; schemaVersion 2.0.0, applicationVersion 1.0.0 dan timestamps.',
    'Snapshot IndexedDB; indikator Unsaved/Saving/Saved locally/error dan Last saved; journal localStorage opsional; migrasi v1 mempertahankan IDs/content.',
    '1. Buat/edit catatan.\n2. Tunggu Saved locally.\n3. Jika error, export snapshot memory sebagai backup.\n4. Import backup jika pindah origin.\n5. Hindari pengeditan concurrent di beberapa tab.',
    'Example SaaS dapat direload pada origin sama; berpindah file:// ke http://127.0.0.1:3001 memerlukan export/import jika storage berbeda.',
    'Semua mutations jadwalkan autosave debounce; Backup mengekspor current workspace; legacy localStorage v1 dipertahankan sesudah migrasi.',
    'Tidak terenkripsi, tidak sync cloud/multiuser, tidak merge konflik tab. IndexedDB = autosave lokal; workspace.json = backup portabel, tidak dibaca/ditulis root otomatis. Recovery journal opsional tidak menggantikan backup. Startup error tidak otomatis menimpa data lama; hindari perubahan sebelum recovery/backup diperiksa.')

add('backup', 'Backup / Restore',
    'Export/import seluruh workspace JSON dengan validasi dan konfirmasi penggantian.',
    'Menghindari kehilangan data browser dan membuat riset dapat dipindahkan.',
    'Rutin, sebelum reset/import, atau ketika berpindah origin/profil browser.',
    'Workspace aktif untuk Export; file JSON v1/v2 maksimal 20 MB untuk Import.',
    'workspace.json atau backup-YYYY-MM-DD.json; workspace diganti jika valid dan dikonfirmasi; JSON invalid ditolak tanpa perubahan.',
    '1. Export Workspace/Export Backup; simpan file.\n2. Backup data aktif sebelum restore.\n3. Import Workspace/Import Backup → pilih JSON.\n4. Review jumlah target dan konfirmasi replace.\n5. Tunggu saved; periksa finding/report.',
    'Backup Example SaaS membawa seluruh target, evidence text/metadata, KB, helper rows, AI suggestions dan report drafts.',
    'Header Export/Import dan halaman Backup memakai actions yang sama; validation/migration dilakukan sebelum store.replace.',
    'Import bukan merge. Screenshot/video binary tidak ikut; simpan terpisah. JSON plaintext perlu dilindungi. Export membaca snapshot memory saat itu; tetap periksa indikator storage untuk durability lokal. Hanya schema v1/v2 yang didukung; invalid refs/duplicate IDs ditolak.', routes=['backup'])

add('connected-file', 'Connect workspace.json — Optional File Save',
    'Menghubungkan file pilihan browser dan menulis workspace saat action Save eksplisit.',
    'Menyediakan backup ke file yang sama tanpa menganggap autosave browser sebagai filesystem save.',
    'Jika browser/context mendukung File System Access API.',
    'File handle dari native picker dan workspace aktif saat Save.',
    'File JSON ditulis hanya pada Save to workspace.json; handle disimpan memory selama session.',
    '1. Settings/Backup → Connect workspace.json.\n2. Pilih lokasi melalui dialog browser.\n3. Tekan Save to workspace.json.\n4. Hubungkan ulang sesudah reload.',
    'Simpan snapshot Example SaaS ke file backup pilihan Anda sesudah satu sesi riset.',
    'Menggunakan snapshot store yang sama dengan Export; IndexedDB autosave tetap terpisah.',
    'Connect bukan import/read-existing-file dan tidak autosave filesystem. Save dapat menimpa file yang dipilih; perhatikan native picker. Jika API tidak tersedia, gunakan download Export biasa.')

add('reset', 'Reset Workspace',
    'Mengosongkan seluruh target dan riset workspace browser aktif setelah konfirmasi.',
    'Memulai workspace baru ketika peneliti sudah menyimpan backup yang diperlukan.',
    'Hanya ketika ingin menghapus seluruh data workspace aktif.',
    'Keputusan peneliti melalui Reset Workspace dan konfirmasi dialog.',
    'Fresh workspace tanpa target, tersimpan melalui autosave. Backup download dan legacy v1 tidak ikut dihapus.',
    '1. Export Backup terlebih dahulu dan periksa file.\n2. Settings/Backup → Reset Workspace.\n3. Baca peringatan seluruh koleksi.\n4. Konfirmasi hanya jika siap kehilangan workspace aktif.',
    'Setelah laboratorium Example SaaS selesai, backup lalu reset sebelum latihan baru.',
    'Menghapus target/hypothesis/test/finding/evidence/knowledge/helper/suggestion/note/report aktif; Backup digunakan untuk restore.',
    'PERINGATAN: reset menghapus semua target, bukan hanya CURRENT TARGET. Tidak ada Undo bawaan; restore memerlukan backup. Ini bukan secure erase file binary/download atau legacy storage.')

add('in-app-help', 'Contextual Help dan Documentation',
    'Tombol ? dengan tooltip singkat, penjelasan purpose/status, dan View Documentation.',
    'Membantu pengguna belajar fitur dari tempat mereka sedang bekerja.',
    'Saat membuka menu/operation/helper yang belum dipahami.',
    'Route aktif, helper/operation pilihan dan metadata featureRegistry.',
    'Dialog help dan tautan langsung ke bagian referensi; halaman HTML dokumentasi lokal dengan daftar isi dan navigasi empat panduan.',
    '1. Arahkan pointer ke ? untuk tooltip.\n2. Klik ? untuk description/purpose/status.\n3. View Documentation membuka bagian yang sesuai.\n4. Ikuti tautan User Guide/Workflow Guide bila perlu.',
    'Pada Trust Boundaries, ? menjelaskan perpindahan trust/authority dan membuka referensi boundary.',
    'Metadata bersama menghasilkan UI help, status, dan Feature Reference. Seluruh menu, helper, dan operasi AI mempunyai entry.',
    'Dokumentasi HTML dibundel lokal dan tidak membutuhkan cloud atau fetch file://. Markdown tetap tersedia pada docs/ untuk dibaca langsung. Tidak ada fitur scanner atau approval eksternal yang tersembunyi dalam bantuan.')

add('target-intelligence','Target Intelligence',
    'Profil bisnis target, klasifikasi sektor multi-domain, knowledge provenance, dan review saran.',
    'Membantu memahami bisnis sebelum menyusun pengujian teknologi.',
    'Sesudah Create Target dan sebelum mapping/technique selection.',
    'Company/Organization, Sector, Industry, Business Model, Company Type, Products, Services, Users, Customer Types, Revenue Model, Important Assets, Sensitive Data, Critical Operations, Dependencies, Technical Surfaces, Notes; primary sector dan secondary domains.',
    'Profil RESEARCHER INPUT, klasifikasi eksplisit, ringkasan domain, accepted knowledge, AI suggestions terpisah; field kosong Unknown.',
    '1. Target Intelligence → Edit Intelligence Profile.\n2. Pilih Primary Sector/Secondary Domains dan Save Domain Classification.\n3. Learn This Domain.\n4. Review domain/AI knowledge.\n5. Import actors/objects atau Convert to Hypothesis melalui editor.',
    'Example Finance memilih Finance primary dan Fintech secondary; company/business model dari catatan laboratorium sendiri, bukan tebakan brand.',
    'Menyimpan target.intelligence; terhubung Domain Knowledge, glossary, flows, invariant, questions, research models, AI context dan backup.',
    'Profil tidak diisi otomatis dari nama perusahaan. Company overview AI menjadi Unknown tanpa TARGET FACT terverifikasi dalam context. Accept tidak membuktikan kebenaran. Tidak ada browsing perusahaan otomatis atau pembuatan finding dari knowledge.',routes=['target-intelligence'])

add('domain-knowledge','Domain Knowledge Packs dan Learning Mode',
    '13 pack generik lokal, custom/override packs, dan materi Beginner/Intermediate/Advanced.',
    'Menghubungkan istilah, pelaku, resource, flow, invariant, dan teknik secara terstruktur.',
    'Sebelum testing dan ketika sektor bisnis belum familiar.',
    'Knowledge Domain pilihan; Learn This Domain; learning depth; Custom Pack fields atau JSON valid; import file maksimal 1 MB.',
    'Overview, terminology, actors, objects, flow, assets, boundaries, invariants, patterns, mapping; override/custom tersimpan pada root domainPacks workspace.',
    '1. Pilih domain.\n2. Learn This Domain dan depth.\n3. Browse Full Pack untuk membuka section lain.\n4. Review/Import actor/object.\n5. + Custom Domain Pack atau Edit Pack JSON.\n6. Edit Flow Relationships dan tambah Technique Mapping bila diperlukan.',
    'Finance menyediakan Account/Ledger/Settlement/Reconciliation dan flow generik transfer. SaaS menyediakan tenancy/membership/resource sharing.',
    'Pack data ada di data/domains; bundled untuk file://. Global Search membaca pack. Selected domain/flow/term menjadi context AI opsional.',
    'Domain knowledge bukan fakta target atau vulnerability. Learning manual tetap aktif tanpa AI. Custom form membuat entri dasar; advanced boundary/question/relationships dapat diedit melalui JSON atau flow relationship editor. Mengedit pack default membuat override workspace; tidak mengubah file static. Restore Default menghapus override, bukan snapshot riset.',routes=['domain-knowledge'])

add('terminology','Domain Terminology',
    'Glossary domain dengan definition, whyImportant, related terms dan provenance.',
    'Mencegah salah menafsirkan proses bisnis sebelum merancang test.',
    'Saat belajar sektor dan meninjau konsep yang muncul dalam flow.',
    'Knowledge Domain dan Search Terminology; term dipilih untuk Explain Terminology AI bila aktif.',
    'Kartu istilah, definisi Indonesia, kaitan istilah, confidence/source; Finance mempunyai 22 istilah awal.',
    '1. Terminology → pilih Finance.\n2. Cari Settlement atau Reconciliation.\n3. Baca definition/whyImportant/related terms.\n4. Ask / Explain Term memilih term pada form AI; preview/send tetap diperlukan.',
    'Ledger adalah catatan pembukuan; Balance adalah posisi saldo; Available Balance adalah bagian yang tersedia setelah pembatasan. Settlement berbeda dari Clearing.',
    'Glossary dari domain pack; Global Search juga menampilkan flow/invariant/technique yang terkait melalui flow text.',
    'Definisi generik harus dibandingkan dengan istilah produk aktual. Materi keuangan bukan nasihat transaksi/kepatuhan. Explain Terminology tidak memanggil provider sebelum preview/send.',routes=['terminology'])

add('business-flows','Business Flows dan Critical Transitions',
    'Flow bisnis terstruktur dengan actor/object/boundary/invariant relationships dan transisi kritis.',
    'Mengubah proses bisnis menjadi pertanyaan keamanan yang mempunyai konteks.',
    'Sesudah memilih domain, sebelum hypothesis dan test.',
    'Selected domain, flow steps, actor/object/boundary/invariant IDs; transition pilihan; Mark/Unmark Critical; Edit Flow Relationships.',
    'Diagram teks flow, relationship list, critical transition, mapped techniques; review question atau draft hypothesis dengan knowledgeLinks.',
    '1. Business Flows → baca langkah.\n2. Pilih transition.\n3. Review tanda CRITICAL.\n4. Edit Flow Relationships untuk melengkapi kaitan.\n5. Flow → Invariant → Question menyimpan hanya setelah review.\n6. Flow → Hypothesis membuka editor riset.',
    'Finance: Create Transfer → Authorization → Ledger Update → Settlement → Reconciliation. Tanyakan apakah authority masih berlaku ketika execution terjadi.',
    'Sector → Flow → Actor/Object → Boundary → Invariant → Technique → Hypothesis → Test → Finding. knowledgeLinks diteruskan sepanjang promotion.',
    'Flow generik bukan proses target yang terbukti. Konversi tidak menjalankan test. Flow AI diterima sebagai draft dengan steps dan provenance; critical transition/invariant untuk flow tersebut harus direview peneliti. Editing hubungan memperbarui override pack, bukan source static.',routes=['business-flows'])

add('critical-assets','Critical Assets dan Sensitive Data',
    'Asset/data bernilai tinggi dari pola domain dan knowledge target yang direview.',
    'Membantu menjelaskan resource terlindungi serta dampak yang perlu dibuktikan.',
    'Saat mapping ownership/authority dan memilih research questions.',
    'Pack criticalAssets/sensitiveData, target profile, accepted item kind asset/sensitive-data.',
    'Kartu sumber/confidence, preview generik dan review/save knowledge.',
    '1. Critical Assets → pilih domain.\n2. Baca resource dan sensitivitas.\n3. Review / Save Knowledge bila relevan.\n4. Lengkapi Objects dan test scope manual.',
    'Account, Ledger Entry, API Credential pada finance adalah kandidat asset bernilai tinggi; belum berarti target memiliki implementasi tertentu.',
    'Domain Pack/Target Knowledge → mapping Objects → Hypotheses/Tests → evidence/impact finding.',
    'Daftar generik tidak memvalidasi kepemilikan atau sensitivitas aktual. Dummy data diperlukan dalam latihan; jangan menyimpan secret karena label asset terlihat umum.',routes=['critical-assets'])

add('research-questions','Domain Research Questions dan Invariant Conversion',
    'Pertanyaan domain/target yang dapat direview lalu dikonversi menjadi hypothesis.',
    'Mengubah pemahaman bisnis menjadi rencana investigasi yang terarah.',
    'Sesudah flow/invariant dipahami dan sebelum manual authorized testing.',
    'Domain researchQuestions, accepted question/invariant, invariant/flow/technique relationships, formula dan scope yang diisi peneliti.',
    'Kartu pertanyaan dan editable hypothesis draft; record baru hanya sesudah Simpan.',
    '1. Research Questions → baca question/invariant.\n2. Review / Save Knowledge bila perlu.\n3. Convert to Hypothesis.\n4. Isi actor/object/state/authority/expected.\n5. Simpan → Buat Test Case.',
    'Apakah revoked beneficiary masih dapat dipakai? Bagaimana worker settlement memvalidasi authority terbaru? Ini pertanyaan generik, bukan temuan.',
    'Flows/Domain Invariants/AI → Questions → existing Hypothesis Engine; knowledgeLinks memuat domain, flow, invariant, question dan sourceType.',
    'Hypothesis tidak otomatis confirmed dan confidence awal tetap low. Jika invariant/mapping belum ada, isi sendiri saat review. Tidak ada evidence atau finding yang dibuat otomatis.',routes=['research-questions'])

add('knowledge-provenance','Knowledge Provenance dan Verification',
    'Memisahkan TARGET FACT, DOMAIN KNOWLEDGE, RESEARCHER INPUT, AI INFERENCE dan UNKNOWN.',
    'Mencegah inferensi perusahaan menjadi fakta hanya karena diterima ke workspace.',
    'Pada setiap profile, domain item, AI suggestion dan imported research record.',
    'sourceType researcher/target/domain/ai/external/unknown; source, confidence 0–1, verified, notes; explicit verification source dan konfirmasi peneliti.',
    'Badge sumber/confidence/verified; AI GENERATED origin dipertahankan ketika peneliti memverifikasi item menjadi target fact.',
    '1. Baca badge dan source.\n2. Accept/Edit menyimpan draft tanpa verifikasi.\n3. Verify as Target Fact hanya setelah memeriksa sumber.\n4. Isi reference dan konfirmasi eksplisit.\n5. Edit content menurunkan verifikasi dan perlu review ulang.',
    'API key sensitif = domain knowledge. Target menyediakan API = target fact hanya bila source/verifikasi ada. Worker mungkin async = AI inference.',
    'Profile/Domain/Accepted Items/Actors/Objects/Boundaries/AI context/Backup menggunakan provenance.',
    'Verified adalah pernyataan peneliti, bukan verifikasi independen software. AI schema menolak source target/verified true. TARGET FACT tanpa source atau verified ditolak. Imported packs boleh merepresentasikan fakta yang diverifikasi peneliti, tetapi tidak berasal dari konfirmasi model otomatis.')

add('knowledge-ai','AI Knowledge Assistant',
    '11 operasi knowledge opsional dengan context pilihan, preview/redaksi, output JSON dan review per item.',
    'Membantu memahami bisnis tanpa mengarang fakta atau menjalankan pengujian.',
    'Sesudah membuat target dan memilih domain; untuk penjelasan, pertanyaan dan saran draft.',
    'Operation; selected domain/term/flow; Question/Goal; Notes; Learning Depth; current hypothesis opsional; privacy mode. Backend/provider config existing.',
    'items dengan kind/title/content/sourceType/confidence/notes/relations/steps; suggestedDomains; unknownInformation. Semua AI items unverified dan inference/unknown.',
    '1. Pilih operation pada form AI Knowledge Assistant.\n2. Pilih term/flow/hypothesis yang relevan.\n3. Preview Knowledge Context.\n4. Send Knowledge Analysis.\n5. Accept/Edit/Reject item atau review sector.\n6. Import/Convert lewat editor terpisah.',
    'Generate Target Knowledge untuk Example Finance menyarankan pola Finance supplied; Company Overview tetap Unknown tanpa target fact terverifikasi.',
    'Shared localhost/config/provider/redactor/policy dengan AI lama, tetapi endpoint/schema knowledge terpisah. Selected knowledge juga dapat masuk Research Assistant lama melalui opt-in Include Knowledge Base.',
    'Tidak ada browsing perusahaan otomatis, provider model default, execution tool, severity atau finding auto. AI_DISABLED tidak menginisialisasi provider; seluruh knowledge manual aktif. Context hanya satu selected pack lengkap terbatas, label katalog domain, capped target knowledge/mapping dan satu hypothesis; bukan seluruh database. Provider nyata belum dibuktikan oleh mock tests.')

KNOWLEDGE_OPS=[
 ('generate_target_knowledge','Generate Target Knowledge','Menyusun draft overview, actors/objects/flows/invariants/questions dari context.','Sebelum mapping riset target.','items berjenis overview/model/actor/object/asset/data/flow/term/boundary/invariant/question dan unknownInformation.'),
 ('analyze_target','Analyze Target','Menganalisis hubungan bisnis dan context target yang supplied.','Saat profil target mulai lengkap.','Penjelasan, missing/unknown informasi dan pertanyaan review.'),
 ('suggest_domains','Suggest Domain','Menyarankan klasifikasi dari label domain yang tersedia.','Sebelum menentukan sektor utama.','suggestedDomains dengan reason/confidence; klasifikasi akhir harus disetujui peneliti.'),
 ('explain_domain','Explain Domain','Menjelaskan domain menurut kedalaman belajar.','Saat mempelajari sektor baru.','Kartu penjelasan concepts/actor/object/flow/invariant, bukan fakta target.'),
 ('explain_terminology','Explain Terminology','Menjelaskan term pilihan dan kaitan bisnis/keamanannya.','Ketika glossary belum cukup jelas.','Item terminology/explanation berlabel AI inference.'),
 ('ask_about_target','Ask About Target','Menjawab question dari target knowledge, domain dan context riset.','Ketika ada pertanyaan bisnis tertentu.','Explanation dan unknownInformation dengan source/confidence.'),
 ('analyze_business_flow','Analyze Business Flow','Menganalisis flow pilihan dan critical transitions.','Sebelum invariant/hypothesis.','Flow/boundary/invariant/question drafts; bukan proses perusahaan confirmed.'),
 ('identify_critical_assets','Identify Critical Assets','Menyarankan resource dan data sensitif yang perlu dipetakan.','Saat mapping ownership/impact.','Asset/sensitive-data items untuk review peneliti.'),
 ('generate_security_invariants','Generate Security Invariants','Mengubah context flow/authority menjadi aturan keamanan kandidat.','Sebelum membuat pertanyaan/test.','Invariant draft dengan domain/flow/technique references yang valid.'),
 ('generate_domain_questions','Generate Research Questions','Membuat pertanyaan riset berdasarkan domain/invariant.','Sesudah mempelajari flow.','Question drafts yang dapat diterima lalu Convert to Hypothesis.'),
 ('recommend_domain_techniques','Recommend Techniques — Domain','Memetakan business context ke teknik yang tersedia dan scope policy.','Saat memilih technique berikutnya.','Item invariant/question/explanation dengan techniqueId yang dibatasi kandidat supplied.')]
for operation,name,description,when,outputs in KNOWLEDGE_OPS:
    add('knowledge-op-'+operation,name,description,'Membantu peneliti memahami context bisnis sambil menjaga provenance.',when,
        'Selected target/domain/term/flow, profile/accepted knowledge dengan provenance, scope/rules, Question/Notes, learning depth, current hypothesis opsional; privacy mode.',outputs,
        '1. Pilih Operation '+name+'.\n2. Isi context relevan.\n3. Preview Knowledge Context → Send Knowledge Analysis.\n4. Review confidence/Unknown.\n5. Accept/Edit/Reject; penerapan ke model riset membutuhkan editor terpisah.',
        'Gunakan Example Finance dan domain Finance untuk latihan. Architecture/roles yang tidak supplied tidak boleh dianggap confirmed.',
        'AI Knowledge Assistant → Target Intelligence → existing mapping/hypothesis workflow setelah persetujuan.',
        'Output memakai schema knowledge yang sama; bagian yang tidak relevan dapat kosong. Tidak ada fetch perusahaan atau eksekusi test. Accept bukan verifikasi fakta.',operation=operation)
